"""
Multi-language airsoft terminology glossary.

Structure: EN term (lowercase) -> {lang_code: translation}
English is the hub language — all lookups go through EN keys.

Languages supported:
  es (Spanish), de (German), fr (French), it (Italian), pt (Portuguese),
  ru (Russian), pl (Polish), uk (Ukrainian), ro (Romanian), nl (Dutch),
  hr (Serbo-Croatian), tr (Turkish), hu (Hungarian), el (Greek),
  cs (Czech), sv (Swedish), ca (Catalan), bg (Bulgarian), da (Danish)
"""

GLOSSARY = {
    # ══════════════════════════════════════════════════════════════
    # WEAPON PARTS
    # ══════════════════════════════════════════════════════════════

    "inner barrel": {
        "es": "cañón interior",
        "de": "Innenlauf",
        "fr": "canon interne",
        "it": "canna interna",
        "pt": "cano interno",
        "ru": "внутренний ствол",
        "pl": "lufa wewnętrzna",
        "uk": "внутрішній стовбур",
        "ro": "țeavă interioară",
        "nl": "binnenloop",
        "hr": "unutarnja cijev",
        "tr": "iç namlu",
        "hu": "belső cső",
        "el": "εσωτερική κάννη",
        "cs": "vnitřní hlaveň",
        "sv": "innerpipa",
        "ca": "canó interior",
        "bg": "вътрешен ствол",
        "da": "indre løb",
    },
    "outer barrel": {
        "es": "cañón exterior",
        "de": "Außenlauf",
        "fr": "canon externe",
        "it": "canna esterna",
        "pt": "cano externo",
        "ru": "внешний ствол",
        "pl": "lufa zewnętrzna",
        "uk": "зовнішній стовбур",
        "ro": "țeavă exterioară",
        "nl": "buitenloop",
        "hr": "vanjska cijev",
        "tr": "dış namlu",
        "hu": "külső cső",
        "el": "εξωτερική κάννη",
        "cs": "vnější hlaveň",
        "sv": "ytterpipa",
        "ca": "canó exterior",
        "bg": "външен ствол",
        "da": "ydre løb",
    },
    "barrel": {
        "es": "cañón",
        "de": "Lauf",
        "fr": "canon",
        "it": "canna",
        "pt": "cano",
        "ru": "ствол",
        "pl": "lufa",
        "uk": "стовбур",
        "ro": "țeavă",
        "nl": "loop",
        "hr": "cijev",
        "tr": "namlu",
        "hu": "cső",
        "el": "κάννη",
        "cs": "hlaveň",
        "sv": "pipa",
        "ca": "canó",
        "bg": "ствол",
        "da": "løb",
    },
    "barrel extension": {
        "es": "extensión de cañón",
        "de": "Laufverlängerung",
        "fr": "extension de canon",
        "it": "estensione canna",
        "pt": "extensão de cano",
        "ru": "удлинитель ствола",
        "pl": "przedłużka lufy",
        "uk": "подовжувач стовбура",
        "ro": "extensie de țeavă",
        "nl": "loopverlenging",
        "hr": "produžetak cijevi",
        "tr": "namlu uzatması",
        "hu": "csőhosszabbító",
        "el": "προέκταση κάννης",
        "cs": "prodloužení hlavně",
        "sv": "pipförlängare",
        "ca": "extensió de canó",
        "bg": "удължител на ствола",
        "da": "løbforlænger",
    },
    "barrel length": {
        "es": "longitud de cañón",
        "de": "Lauflänge",
        "fr": "longueur de canon",
        "it": "lunghezza canna",
        "pt": "comprimento do cano",
        "ru": "длина ствола",
        "pl": "długość lufy",
        "uk": "довжина стовбура",
        "ro": "lungimea țevii",
        "nl": "looplengte",
        "hr": "duljina cijevi",
        "tr": "namlu uzunluğu",
        "hu": "csőhossz",
        "el": "μήκος κάννης",
        "cs": "délka hlavně",
        "sv": "piplängd",
        "ca": "longitud del canó",
        "bg": "дължина на ствола",
        "da": "løblængde",
    },
    "hop-up": {
        "es": "hop-up", "de": "Hop-Up", "fr": "hop-up", "it": "hop-up",
        "pt": "hop-up", "ru": "хоп-ап", "pl": "hop-up", "uk": "хоп-ап",
        "ro": "hop-up", "nl": "hop-up", "hr": "hop-up", "tr": "hop-up",
        "hu": "hop-up", "el": "hop-up", "cs": "hop-up", "sv": "hop-up",
        "ca": "hop-up", "bg": "хоп-ъп", "da": "hop-up",
    },
    "hop-up chamber": {
        "es": "cámara de hop-up",
        "de": "Hop-Up-Kammer",
        "fr": "chambre de hop-up",
        "it": "camera hop-up",
        "pt": "câmara de hop-up",
        "ru": "камера хоп-апа",
        "pl": "komora hop-up",
        "uk": "камера хоп-апу",
        "ro": "cameră hop-up",
        "nl": "hop-up kamer",
        "hr": "hop-up komora",
        "tr": "hop-up haznesi",
        "hu": "hop-up kamra",
        "el": "θάλαμος hop-up",
        "cs": "hop-up komora",
        "sv": "hop-up-kammare",
        "ca": "cambra de hop-up",
        "bg": "камера на хоп-ъп",
        "da": "hop-up kammer",
    },
    "hop-up bucking": {
        "es": "goma de hop-up",
        "de": "Hop-Up-Gummi",
        "fr": "joint de hop-up",
        "it": "gommino hop-up",
        "pt": "borracha de hop-up",
        "ru": "резинка хоп-апа",
        "pl": "gumka hop-up",
        "uk": "гумка хоп-апу",
        "ro": "cauciuc hop-up",
        "nl": "hop-up rubber",
        "hr": "hop-up gumica",
        "tr": "hop-up lastiği",
        "hu": "hop-up gumi",
        "el": "λάστιχο hop-up",
        "cs": "hop-up gumička",
        "sv": "hop-up-gummi",
        "ca": "goma de hop-up",
        "bg": "гумичка за хоп-ъп",
        "da": "hop-up gummi",
    },
    "hop-up nub": {
        "es": "nub de hop-up", "de": "Hop-Up-Nub", "fr": "nub de hop-up",
        "it": "nub hop-up", "pt": "nub de hop-up", "ru": "наб хоп-апа",
        "pl": "nub hop-up", "uk": "наб хоп-апу", "ro": "nub hop-up",
        "nl": "hop-up nub", "hr": "hop-up nub", "tr": "hop-up nub",
        "hu": "hop-up nub", "el": "nub hop-up", "cs": "hop-up nub",
        "sv": "hop-up-nub", "ca": "nub de hop-up", "bg": "наб за хоп-ъп",
        "da": "hop-up nub",
    },
    "gearbox": {
        "es": "gearbox", "de": "Gearbox", "fr": "gearbox", "it": "gearbox",
        "pt": "gearbox", "ru": "гирбокс", "pl": "gearbox", "uk": "гірбокс",
        "ro": "gearbox", "nl": "gearbox", "hr": "gearbox", "tr": "gearbox",
        "hu": "gearbox", "el": "gearbox", "cs": "gearbox", "sv": "gearbox",
        "ca": "gearbox", "bg": "гиърбокс", "da": "gearbox",
    },
    "gearbox shell": {
        "es": "carcasa de gearbox",
        "de": "Gearbox-Gehäuse",
        "fr": "coque de gearbox",
        "it": "guscio gearbox",
        "pt": "carcaça de gearbox",
        "ru": "корпус гирбокса",
        "pl": "szkielet gearboxa",
        "uk": "корпус гірбоксу",
        "ro": "carcasă gearbox",
        "nl": "gearbox behuizing",
        "hr": "kućište gearboxa",
        "tr": "gearbox gövdesi",
        "hu": "gearbox ház",
        "el": "κέλυφος gearbox",
        "cs": "tělo gearboxu",
        "sv": "gearbox-skal",
        "ca": "carcassa de gearbox",
        "bg": "корпус на гиърбокс",
        "da": "gearbox hus",
    },
    "cylinder": {
        "es": "cilindro", "de": "Zylinder", "fr": "cylindre", "it": "cilindro",
        "pt": "cilindro", "ru": "цилиндр", "pl": "cylinder", "uk": "циліндр",
        "ro": "cilindru", "nl": "cilinder", "hr": "cilindar", "tr": "silindir",
        "hu": "henger", "el": "κύλινδρος", "cs": "válec", "sv": "cylinder",
        "ca": "cilindre", "bg": "цилиндър", "da": "cylinder",
    },
    "cylinder head": {
        "es": "cabeza de cilindro",
        "de": "Zylinderkopf",
        "fr": "tête de cylindre",
        "it": "testa cilindro",
        "pt": "cabeça de cilindro",
        "ru": "голова цилиндра",
        "pl": "głowica cylindra",
        "uk": "голова циліндра",
        "ro": "cap cilindru",
        "nl": "cilinderkop",
        "hr": "glava cilindra",
        "tr": "silindir kafası",
        "hu": "hengerfej",
        "el": "κεφαλή κυλίνδρου",
        "cs": "hlava válce",
        "sv": "cylinderhuvud",
        "ca": "cap de cilindre",
        "bg": "глава на цилиндъра",
        "da": "cylinderhoved",
    },
    "piston": {
        "es": "pistón", "de": "Kolben", "fr": "piston", "it": "pistone",
        "pt": "pistão", "ru": "поршень", "pl": "tłok", "uk": "поршень",
        "ro": "piston", "nl": "zuiger", "hr": "klip", "tr": "piston",
        "hu": "dugattyú", "el": "έμβολο", "cs": "píst", "sv": "kolv",
        "ca": "pistó", "bg": "бутало", "da": "stempel",
    },
    "piston head": {
        "es": "cabeza de pistón",
        "de": "Kolbenkopf",
        "fr": "tête de piston",
        "it": "testa pistone",
        "pt": "cabeça de pistão",
        "ru": "голова поршня",
        "pl": "głowica tłoka",
        "uk": "голова поршня",
        "ro": "cap piston",
        "nl": "zuigerkop",
        "hr": "glava klipa",
        "tr": "piston kafası",
        "hu": "dugattyúfej",
        "el": "κεφαλή εμβόλου",
        "cs": "hlava pístu",
        "sv": "kolvhuvud",
        "ca": "cap de pistó",
        "bg": "глава на буталото",
        "da": "stempelhoved",
    },
    "spring": {
        "es": "muelle", "de": "Feder", "fr": "ressort", "it": "molla",
        "pt": "mola", "ru": "пружина", "pl": "sprężyna", "uk": "пружина",
        "ro": "arc", "nl": "veer", "hr": "opruga", "tr": "yay",
        "hu": "rugó", "el": "ελατήριο", "cs": "pružina", "sv": "fjäder",
        "ca": "molla", "bg": "пружина", "da": "fjeder",
    },
    "spring guide": {
        "es": "guía de muelle",
        "de": "Federführung",
        "fr": "guide de ressort",
        "it": "guida molla",
        "pt": "guia de mola",
        "ru": "направляющая пружины",
        "pl": "prowadnica sprężyny",
        "uk": "напрямна пружини",
        "ro": "ghid de arc",
        "nl": "veergeleider",
        "hr": "vodilica opruge",
        "tr": "yay kılavuzu",
        "hu": "rugóvezető",
        "el": "οδηγός ελατηρίου",
        "cs": "vedení pružiny",
        "sv": "fjäderguide",
        "ca": "guia de molla",
        "bg": "водач на пружина",
        "da": "fjederguide",
    },
    "nozzle": {
        "es": "nozzle", "de": "Nozzle", "fr": "nozzle", "it": "nozzle",
        "pt": "nozzle", "ru": "ноззл", "pl": "nozzle", "uk": "нозл",
        "ro": "nozzle", "nl": "nozzle", "hr": "nozzle", "tr": "nozzle",
        "hu": "nozzle", "el": "nozzle", "cs": "nozzle", "sv": "nozzle",
        "ca": "nozzle", "bg": "нозъл", "da": "nozzle",
    },
    "air nozzle": {
        "es": "nozzle de aire", "de": "Luftdüse", "fr": "nozzle d'air",
        "it": "nozzle aria", "pt": "nozzle de ar", "ru": "воздушная форсунка",
        "pl": "dysza powietrza", "uk": "повітряна форсунка", "ro": "duză de aer",
        "nl": "luchtnozzle", "hr": "zračna mlaznica", "tr": "hava nozulu",
        "hu": "levegő fúvóka", "el": "ακροφύσιο αέρα", "cs": "vzduchová tryska",
        "sv": "luftmunstycke", "ca": "nozzle d'aire", "bg": "въздушна дюза",
        "da": "luftdyse",
    },
    "tappet plate": {
        "es": "tappet plate", "de": "Tappet Plate", "fr": "tappet plate",
        "it": "tappet plate", "pt": "tappet plate", "ru": "таппет плейт",
        "pl": "tappet plate", "uk": "таппет плейт", "ro": "tappet plate",
        "nl": "tappet plate", "hr": "tappet plate", "tr": "tappet plate",
        "hu": "tappet plate", "el": "tappet plate", "cs": "tappet plate",
        "sv": "tappet plate", "ca": "tappet plate", "bg": "тапет плейт",
        "da": "tappet plate",
    },
    "trigger": {
        "es": "gatillo", "de": "Abzug", "fr": "détente", "it": "grilletto",
        "pt": "gatilho", "ru": "спусковой крючок", "pl": "spust", "uk": "спусковий гачок",
        "ro": "trăgaci", "nl": "trekker", "hr": "okidač", "tr": "tetik",
        "hu": "ravasz", "el": "σκανδάλη", "cs": "spoušť", "sv": "avtryckare",
        "ca": "gallet", "bg": "спусък", "da": "aftrækkker",
    },
    "trigger unit": {
        "es": "unidad de gatillo",
        "de": "Abzugseinheit",
        "fr": "unité de détente",
        "it": "unità grilletto",
        "pt": "unidade de gatilho",
        "ru": "спусковой механизм",
        "pl": "mechanizm spustowy",
        "uk": "спусковий механізм",
        "ro": "mecanism de trăgaci",
        "nl": "trekkermechanisme",
        "hr": "okidačka jedinica",
        "tr": "tetik ünitesi",
        "hu": "elsütő mechanizmus",
        "el": "μηχανισμός σκανδάλης",
        "cs": "spouštěcí mechanismus",
        "sv": "avtryckarenhet",
        "ca": "unitat de gallet",
        "bg": "спусков механизъм",
        "da": "aftrækkerenhed",
    },
    "trigger guard": {
        "es": "guardamonte", "de": "Abzugsbügel", "fr": "pontet",
        "it": "ponticello", "pt": "guarda-mato", "ru": "спусковая скоба",
        "pl": "kabłąk spustowy", "uk": "спускова скоба", "ro": "apărătoarea trăgaciului",
        "nl": "trekkerbeugel", "hr": "branik okidača", "tr": "tetik muhafazası",
        "hu": "elsütőbillentyű-kengyel", "el": "προφυλακτήρας σκανδάλης",
        "cs": "lučík spouště", "sv": "avtryckarskydd", "ca": "guardamunt",
        "bg": "спусков предпазител", "da": "aftrækkerbøjle",
    },
    "selector plate": {
        "es": "selector de tiro", "de": "Selectorplatte", "fr": "sélecteur de tir",
        "it": "selettore di tiro", "pt": "seletor de tiro", "ru": "селекторная пластина",
        "pl": "płytka selektora", "uk": "селекторна пластина", "ro": "placă selector",
        "nl": "selectorplaat", "hr": "selektor ploča", "tr": "seçici plakası",
        "hu": "szelektor lemez", "el": "πλάκα επιλογέα", "cs": "selectorová destička",
        "sv": "selektorplatta", "ca": "selector de tir", "bg": "селекторна пластина",
        "da": "selectorplade",
    },
    "fire selector": {
        "es": "selector de tiro", "de": "Feuermodus-Wähler", "fr": "sélecteur de tir",
        "it": "selettore di tiro", "pt": "seletor de tiro", "ru": "переводчик огня",
        "pl": "przełącznik ognia", "uk": "перемикач вогню", "ro": "selector de foc",
        "nl": "vuurkeuze schakelaar", "hr": "selektor vatre", "tr": "ateş seçici",
        "hu": "tűzváltó", "el": "επιλογέας πυρός", "cs": "přepínač palby",
        "sv": "eldväljare", "ca": "selector de foc", "bg": "превключвател на огъня",
        "da": "ildvælger",
    },
    "safety": {
        "es": "seguro", "de": "Sicherung", "fr": "sécurité", "it": "sicura",
        "pt": "trava de segurança", "ru": "предохранитель", "pl": "bezpiecznik",
        "uk": "запобіжник", "ro": "siguranță", "nl": "veiligheidspal",
        "hr": "osigurač", "tr": "emniyet", "hu": "biztosíték",
        "el": "ασφάλεια", "cs": "pojistka", "sv": "säkring",
        "ca": "seguretat", "bg": "предпазител", "da": "sikring",
    },
    "safety lever": {
        "es": "palanca de seguro", "de": "Sicherungshebel", "fr": "levier de sécurité",
        "it": "leva di sicura", "pt": "alavanca de segurança", "ru": "рычаг предохранителя",
        "pl": "dźwignia bezpiecznika", "uk": "важіль запобіжника", "ro": "manetă siguranță",
        "nl": "veiligheidshendel", "hr": "poluga osigurača", "tr": "emniyet kolu",
        "hu": "biztosítókar", "el": "μοχλός ασφαλείας", "cs": "páka pojistky",
        "sv": "säkringsspak", "ca": "palanca de seguretat", "bg": "лост на предпазителя",
        "da": "sikringsgreb",
    },
    "stock": {
        "es": "culata", "de": "Schaft", "fr": "crosse", "it": "calcio",
        "pt": "coronha", "ru": "приклад", "pl": "kolba", "uk": "приклад",
        "ro": "pat", "nl": "kolf", "hr": "kundak", "tr": "dipçik",
        "hu": "tus", "el": "κοντάκι", "cs": "pažba", "sv": "kolv",
        "ca": "culata", "bg": "приклад", "da": "kolbe",
    },
    "folding stock": {
        "es": "culata plegable", "de": "Klappschaft", "fr": "crosse pliante",
        "it": "calcio pieghevole", "pt": "coronha dobrável", "ru": "складной приклад",
        "pl": "kolba składana", "uk": "складний приклад", "ro": "pat pliabil",
        "nl": "opvouwbare kolf", "hr": "sklopivi kundak", "tr": "katlanır dipçik",
        "hu": "összehajtható tus", "el": "αναδιπλούμενο κοντάκι", "cs": "sklopná pažba",
        "sv": "fällbar kolv", "ca": "culata plegable", "bg": "сгъваем приклад",
        "da": "foldbar kolbe",
    },
    "retractable stock": {
        "es": "culata retráctil", "de": "Schiebeschaft", "fr": "crosse rétractable",
        "it": "calcio retraibile", "pt": "coronha retrátil", "ru": "выдвижной приклад",
        "pl": "kolba wysuwana", "uk": "висувний приклад", "ro": "pat retractabil",
        "nl": "intrekbare kolf", "hr": "uvlačivi kundak", "tr": "geri çekilebilir dipçik",
        "hu": "behúzható tus", "el": "ανασυρόμενο κοντάκι", "cs": "zasouvací pažba",
        "sv": "utdragbar kolv", "ca": "culata retràctil", "bg": "прибиращ се приклад",
        "da": "udtrækkelig kolbe",
    },
    "adjustable stock": {
        "es": "culata ajustable", "de": "verstellbarer Schaft", "fr": "crosse réglable",
        "it": "calcio regolabile", "pt": "coronha ajustável", "ru": "регулируемый приклад",
        "pl": "kolba regulowana", "uk": "регульований приклад", "ro": "pat reglabil",
        "nl": "verstelbare kolf", "hr": "podesivi kundak", "tr": "ayarlanabilir dipçik",
        "hu": "állítható tus", "el": "ρυθμιζόμενο κοντάκι", "cs": "nastavitelná pažba",
        "sv": "justerbar kolv", "ca": "culata ajustable", "bg": "регулируем приклад",
        "da": "justerbar kolbe",
    },
    "buffer tube": {
        "es": "tubo de culata", "de": "Pufferrohr", "fr": "tube de crosse",
        "it": "tubo di calcio", "pt": "tubo de coronha", "ru": "буферная трубка",
        "pl": "rura kolby", "uk": "буферна трубка", "ro": "tub buffer",
        "nl": "bufferbuis", "hr": "tampon cijev", "tr": "tampon tüpü",
        "hu": "puffercső", "el": "σωλήνας buffer", "cs": "buffer tube",
        "sv": "buffertrör", "ca": "tub de culata", "bg": "буферна тръба",
        "da": "bufferrør",
    },
    "handguard": {
        "es": "guardamanos", "de": "Handschutz", "fr": "garde-main",
        "it": "paramano", "pt": "guarda-mão", "ru": "цевьё",
        "pl": "łoże", "uk": "цівка", "ro": "apărătoare de mână",
        "nl": "handgreepbeschermer", "hr": "rukobran", "tr": "el koruyucu",
        "hu": "kézvédő", "el": "χειροφυλακτήρας", "cs": "předpažbí",
        "sv": "handskydd", "ca": "guardamans", "bg": "ръкохватка",
        "da": "håndbeskytter",
    },
    "rail": {
        "es": "riel", "de": "Schiene", "fr": "rail", "it": "slitta",
        "pt": "trilho", "ru": "планка", "pl": "szyna", "uk": "планка",
        "ro": "șină", "nl": "rail", "hr": "šina", "tr": "ray",
        "hu": "sín", "el": "ράγα", "cs": "lišta", "sv": "räls",
        "ca": "rail", "bg": "релса", "da": "skinne",
    },
    "rail system": {
        "es": "sistema de rieles", "de": "Schienensystem", "fr": "système de rails",
        "it": "sistema di slitte", "pt": "sistema de trilhos", "ru": "система планок",
        "pl": "system szyn", "uk": "система планок", "ro": "sistem de șine",
        "nl": "railsysteem", "hr": "sustav šina", "tr": "ray sistemi",
        "hu": "sínrendszer", "el": "σύστημα ράγας", "cs": "systém lišt",
        "sv": "rälssystem", "ca": "sistema de rails", "bg": "система от релси",
        "da": "skinnesystem",
    },
    "picatinny rail": {
        "es": "riel Picatinny", "de": "Picatinny-Schiene", "fr": "rail Picatinny",
        "it": "slitta Picatinny", "pt": "trilho Picatinny", "ru": "планка Пикатинни",
        "pl": "szyna Picatinny", "uk": "планка Пікатінні", "ro": "șină Picatinny",
        "nl": "Picatinny rail", "hr": "Picatinny šina", "tr": "Picatinny rayı",
        "hu": "Picatinny sín", "el": "ράγα Picatinny", "cs": "Picatinny lišta",
        "sv": "Picatinny-räls", "ca": "rail Picatinny", "bg": "Picatinny релса",
        "da": "Picatinny-skinne",
    },
    "upper receiver": {
        "es": "cuerpo superior", "de": "Oberteil", "fr": "partie supérieure",
        "it": "corpo superiore", "pt": "corpo superior", "ru": "верхний ресивер",
        "pl": "górna komora zamkowa", "uk": "верхній ресівер", "ro": "receptor superior",
        "nl": "bovenlichaam", "hr": "gornji prijemnik", "tr": "üst gövde",
        "hu": "felső tok", "el": "άνω δέκτης", "cs": "horní tělo",
        "sv": "övre kropp", "ca": "cos superior", "bg": "горен корпус",
        "da": "overkrop",
    },
    "lower receiver": {
        "es": "cuerpo inferior", "de": "Unterteil", "fr": "partie inférieure",
        "it": "corpo inferiore", "pt": "corpo inferior", "ru": "нижний ресивер",
        "pl": "dolna komora zamkowa", "uk": "нижній ресівер", "ro": "receptor inferior",
        "nl": "onderlichaam", "hr": "donji prijemnik", "tr": "alt gövde",
        "hu": "alsó tok", "el": "κάτω δέκτης", "cs": "dolní tělo",
        "sv": "nedre kropp", "ca": "cos inferior", "bg": "долен корпус",
        "da": "underkrop",
    },
    "receiver": {
        "es": "cuerpo", "de": "Gehäuse", "fr": "corps", "it": "corpo",
        "pt": "corpo", "ru": "ресивер", "pl": "komora zamkowa", "uk": "ресівер",
        "ro": "receptor", "nl": "lichaam", "hr": "prijemnik", "tr": "gövde",
        "hu": "tok", "el": "δέκτης", "cs": "tělo", "sv": "kropp",
        "ca": "cos", "bg": "корпус", "da": "krop",
    },
    "bolt": {
        "es": "cerrojo", "de": "Verschluss", "fr": "culasse", "it": "otturatore",
        "pt": "ferrolho", "ru": "затвор", "pl": "zamek", "uk": "затвор",
        "ro": "închizător", "nl": "grendel", "hr": "zatvarač", "tr": "sürgü",
        "hu": "zár", "el": "κλείστρο", "cs": "závěr", "sv": "slutstycke",
        "ca": "forrellat", "bg": "затвор", "da": "bolt",
    },
    "charging handle": {
        "es": "manija de carga", "de": "Ladegriff", "fr": "levier d'armement",
        "it": "leva di armamento", "pt": "alavanca de carregamento",
        "ru": "рукоятка заряжания", "pl": "rączka przeładowania",
        "uk": "рукоятка заряджання", "ro": "manetă de armare",
        "nl": "laadgreep", "hr": "ručka za napinjanje", "tr": "şarj kolu",
        "hu": "felhúzókar", "el": "μοχλός οπλισμού", "cs": "natažení závěru",
        "sv": "laddhandtag", "ca": "maneta de càrrega", "bg": "ръкохватка за зареждане",
        "da": "ladegreb",
    },
    "flash hider": {
        "es": "apagallamas", "de": "Mündungsfeuerdämpfer", "fr": "cache-flamme",
        "it": "rompifiamma", "pt": "quebra-chamas", "ru": "пламегаситель",
        "pl": "tłumik płomienia", "uk": "полумʼягасник", "ro": "parascântei",
        "nl": "vlamdemper", "hr": "prigušivač plamena", "tr": "alev gizleyici",
        "hu": "lángrejtő", "el": "κρύπτης φλόγας", "cs": "tlumič plamene",
        "sv": "flamdämpare", "ca": "paraflames", "bg": "пламегасител",
        "da": "flammeskjuler",
    },
    "muzzle brake": {
        "es": "freno de boca", "de": "Mündungsbremse", "fr": "frein de bouche",
        "it": "freno di bocca", "pt": "freio de boca", "ru": "дульный тормоз",
        "pl": "hamulec wylotowy", "uk": "дульне гальмо", "ro": "frână de gură",
        "nl": "mondingsrem", "hr": "kočnica usta", "tr": "namlu freni",
        "hu": "csőszájfék", "el": "φρένο στομίου", "cs": "úsťová brzda",
        "sv": "mynningsbroms", "ca": "fre de boca", "bg": "дулен спирач",
        "da": "mundingsbremse",
    },
    "suppressor": {
        "es": "silenciador", "de": "Schalldämpfer", "fr": "silencieux",
        "it": "silenziatore", "pt": "silenciador", "ru": "глушитель",
        "pl": "tłumik", "uk": "глушник", "ro": "amortizor de sunet",
        "nl": "demper", "hr": "prigušivač", "tr": "susturucu",
        "hu": "hangtompító", "el": "σιγαστήρας", "cs": "tlumič",
        "sv": "ljuddämpare", "ca": "silenciador", "bg": "заглушител",
        "da": "lyddæmper",
    },
    "silencer": {
        "es": "silenciador", "de": "Schalldämpfer", "fr": "silencieux",
        "it": "silenziatore", "pt": "silenciador", "ru": "глушитель",
        "pl": "tłumik", "uk": "глушник", "ro": "amortizor de sunet",
        "nl": "demper", "hr": "prigušivač", "tr": "susturucu",
        "hu": "hangtompító", "el": "σιγαστήρας", "cs": "tlumič",
        "sv": "ljuddämpare", "ca": "silenciador", "bg": "заглушител",
        "da": "lyddæmper",
    },
    "tracer unit": {
        "es": "unidad trazadora", "de": "Tracer-Einheit", "fr": "unité tracer",
        "it": "unità tracer", "pt": "unidade tracer", "ru": "трассерная насадка",
        "pl": "nakładka tracer", "uk": "трасерна насадка", "ro": "unitate tracer",
        "nl": "tracer unit", "hr": "tracer jedinica", "tr": "tracer ünitesi",
        "hu": "tracer egység", "el": "μονάδα tracer", "cs": "tracer jednotka",
        "sv": "tracerenhet", "ca": "unitat tracer", "bg": "трасиращо устройство",
        "da": "tracerenhed",
    },
    "grip": {
        "es": "empuñadura", "de": "Griff", "fr": "poignée", "it": "impugnatura",
        "pt": "empunhadura", "ru": "рукоятка", "pl": "chwyt", "uk": "рукоятка",
        "ro": "mâner", "nl": "greep", "hr": "rukohvat", "tr": "kabza",
        "hu": "markolat", "el": "λαβή", "cs": "rukojeť", "sv": "grepp",
        "ca": "empunyadura", "bg": "ръкохватка", "da": "greb",
    },
    "pistol grip": {
        "es": "empuñadura de pistola", "de": "Pistolengriff", "fr": "poignée pistolet",
        "it": "impugnatura a pistola", "pt": "empunhadura tipo pistola",
        "ru": "пистолетная рукоятка", "pl": "chwyt pistoletowy",
        "uk": "пістолетна рукоятка", "ro": "mâner de pistol",
        "nl": "pistoolgreep", "hr": "pištoljski rukohvat", "tr": "tabanca kabzası",
        "hu": "pisztolymarkolat", "el": "λαβή πιστολιού", "cs": "pistolová rukojeť",
        "sv": "pistolgrepp", "ca": "empunyadura de pistola", "bg": "пистолетна ръкохватка",
        "da": "pistolgreb",
    },
    "foregrip": {
        "es": "empuñadura delantera", "de": "Vordergriff", "fr": "poignée avant",
        "it": "impugnatura anteriore", "pt": "empunhadura dianteira",
        "ru": "передняя рукоятка", "pl": "chwyt przedni",
        "uk": "передня рукоятка", "ro": "mâner frontal",
        "nl": "voorgreep", "hr": "prednji rukohvat", "tr": "ön kabza",
        "hu": "előmarkolat", "el": "εμπρόσθια λαβή", "cs": "přední rukojeť",
        "sv": "framgrepp", "ca": "empunyadura davantera", "bg": "предна ръкохватка",
        "da": "frontgreb",
    },
    "magazine": {
        "es": "cargador", "de": "Magazin", "fr": "chargeur", "it": "caricatore",
        "pt": "carregador", "ru": "магазин", "pl": "magazynek", "uk": "магазин",
        "ro": "încărcător", "nl": "magazijn", "hr": "spremnik", "tr": "şarjör",
        "hu": "tár", "el": "γεμιστήρας", "cs": "zásobník", "sv": "magasin",
        "ca": "carregador", "bg": "пълнител", "da": "magasin",
    },
    "mag": {
        "es": "cargador", "de": "Magazin", "fr": "chargeur", "it": "caricatore",
        "pt": "carregador", "ru": "магазин", "pl": "magazynek", "uk": "магазин",
        "ro": "încărcător", "nl": "magazijn", "hr": "spremnik", "tr": "şarjör",
        "hu": "tár", "el": "γεμιστήρας", "cs": "zásobník", "sv": "magasin",
        "ca": "carregador", "bg": "пълнител", "da": "magasin",
    },
    "mid-cap magazine": {
        "es": "cargador mid-cap", "de": "Mid-Cap Magazin", "fr": "chargeur mid-cap",
        "it": "caricatore mid-cap", "pt": "carregador mid-cap", "ru": "магазин mid-cap",
        "pl": "magazynek mid-cap", "uk": "магазин mid-cap", "ro": "încărcător mid-cap",
        "nl": "mid-cap magazijn", "hr": "mid-cap spremnik", "tr": "mid-cap şarjör",
        "hu": "mid-cap tár", "el": "γεμιστήρας mid-cap", "cs": "mid-cap zásobník",
        "sv": "mid-cap magasin", "ca": "carregador mid-cap", "bg": "mid-cap пълнител",
        "da": "mid-cap magasin",
    },
    "hi-cap magazine": {
        "es": "cargador hi-cap", "de": "Hi-Cap Magazin", "fr": "chargeur hi-cap",
        "it": "caricatore hi-cap", "pt": "carregador hi-cap", "ru": "магазин hi-cap",
        "pl": "magazynek hi-cap", "uk": "магазин hi-cap", "ro": "încărcător hi-cap",
        "nl": "hi-cap magazijn", "hr": "hi-cap spremnik", "tr": "hi-cap şarjör",
        "hu": "hi-cap tár", "el": "γεμιστήρας hi-cap", "cs": "hi-cap zásobník",
        "sv": "hi-cap magasin", "ca": "carregador hi-cap", "bg": "hi-cap пълнител",
        "da": "hi-cap magasin",
    },
    "drum magazine": {
        "es": "cargador de tambor", "de": "Trommelmagazin", "fr": "chargeur tambour",
        "it": "caricatore a tamburo", "pt": "carregador tambor", "ru": "барабанный магазин",
        "pl": "magazynek bębnowy", "uk": "барабанний магазин", "ro": "încărcător tambur",
        "nl": "trommelmagazijn", "hr": "bubanj spremnik", "tr": "tambur şarjör",
        "hu": "dobtár", "el": "τυμπανοειδής γεμιστήρας", "cs": "bubnový zásobník",
        "sv": "trummagasin", "ca": "carregador de tambor", "bg": "барабанен пълнител",
        "da": "tromlemagasin",
    },
    "mag release": {
        "es": "liberador de cargador", "de": "Magazinauslöser", "fr": "largueur de chargeur",
        "it": "sgancio caricatore", "pt": "liberador de carregador",
        "ru": "кнопка сброса магазина", "pl": "zwalniacz magazynka",
        "uk": "кнопка скидання магазину", "ro": "eliberare încărcător",
        "nl": "magazijnontgrendeling", "hr": "otpuštanje spremnika", "tr": "şarjör düğmesi",
        "hu": "tárkireteszelő", "el": "απελευθέρωση γεμιστήρα", "cs": "pojistka zásobníku",
        "sv": "magasinfrigöring", "ca": "alliberador de carregador", "bg": "бутон за освобождаване на пълнителя",
        "da": "magasinudløser",
    },
    "speed loader": {
        "es": "cargador rápido", "de": "Speedloader", "fr": "speed loader",
        "it": "speed loader", "pt": "speed loader", "ru": "спидлоадер",
        "pl": "speed loader", "uk": "спідлоадер", "ro": "speed loader",
        "nl": "speed loader", "hr": "speed loader", "tr": "hızlı doldurucu",
        "hu": "speed loader", "el": "speed loader", "cs": "speed loader",
        "sv": "speed loader", "ca": "carregador ràpid", "bg": "спийдлоудър",
        "da": "speed loader",
    },

    # ══════════════════════════════════════════════════════════════
    # WEAPON TYPES
    # ══════════════════════════════════════════════════════════════

    "airsoft gun": {
        "es": "réplica de airsoft", "de": "Airsoft-Waffe", "fr": "réplique airsoft",
        "it": "replica airsoft", "pt": "réplica de airsoft", "ru": "страйкбольное оружие",
        "pl": "replika ASG", "uk": "страйкбольна зброя", "ro": "replică airsoft",
        "nl": "airsoft replica", "hr": "airsoft replika", "tr": "airsoft silahı",
        "hu": "airsoft fegyver", "el": "airsoft όπλο", "cs": "airsoftová zbraň",
        "sv": "airsoftvapen", "ca": "rèplica d'airsoft", "bg": "еърсофт оръжие",
        "da": "airsoft våben",
    },
    "airsoft rifle": {
        "es": "réplica de airsoft tipo rifle", "de": "Airsoft-Gewehr", "fr": "fusil airsoft",
        "it": "fucile airsoft", "pt": "rifle de airsoft", "ru": "страйкбольная винтовка",
        "pl": "karabin ASG", "uk": "страйкбольна гвинтівка", "ro": "pușcă airsoft",
        "nl": "airsoft geweer", "hr": "airsoft puška", "tr": "airsoft tüfek",
        "hu": "airsoft puska", "el": "airsoft τυφέκιο", "cs": "airsoftová puška",
        "sv": "airsoftgevär", "ca": "fusell d'airsoft", "bg": "еърсофт пушка",
        "da": "airsoft riffel",
    },
    "airsoft pistol": {
        "es": "pistola de airsoft", "de": "Airsoft-Pistole", "fr": "pistolet airsoft",
        "it": "pistola airsoft", "pt": "pistola de airsoft", "ru": "страйкбольный пистолет",
        "pl": "pistolet ASG", "uk": "страйкбольний пістолет", "ro": "pistol airsoft",
        "nl": "airsoft pistool", "hr": "airsoft pištolj", "tr": "airsoft tabanca",
        "hu": "airsoft pisztoly", "el": "airsoft πιστόλι", "cs": "airsoftová pistole",
        "sv": "airsoftpistol", "ca": "pistola d'airsoft", "bg": "еърсофт пистолет",
        "da": "airsoft pistol",
    },
    "replica": {
        "es": "réplica", "de": "Replik", "fr": "réplique", "it": "replica",
        "pt": "réplica", "ru": "реплика", "pl": "replika", "uk": "репліка",
        "ro": "replică", "nl": "replica", "hr": "replika", "tr": "replika",
        "hu": "replika", "el": "ρέπλικα", "cs": "replika", "sv": "replika",
        "ca": "rèplica", "bg": "реплика", "da": "replika",
    },
    "AEG": {
        "es": "AEG (fusil eléctrico automático)", "de": "AEG (Automatik-Elektro-Gewehr)",
        "fr": "AEG (fusil électrique automatique)", "it": "AEG (fucile elettrico automatico)",
        "pt": "AEG (arma elétrica automática)", "ru": "AEG (автоматический электропневматический привод)",
        "pl": "AEG (automatyczny karabin elektryczny)", "uk": "AEG (автоматичний електропневматичний привід)",
        "ro": "AEG (armă electrică automată)", "nl": "AEG (automatisch elektrisch geweer)",
        "hr": "AEG (automatska električna puška)", "tr": "AEG (otomatik elektrikli tüfek)",
        "hu": "AEG (automata elektromos fegyver)", "el": "AEG (αυτόματο ηλεκτρικό όπλο)",
        "cs": "AEG (automatická elektrická zbraň)", "sv": "AEG (automatiskt elgevär)",
        "ca": "AEG (fusell elèctric automàtic)", "bg": "AEG (автоматичен електрически привод)",
        "da": "AEG (automatisk elektrisk gevær)",
    },
    "GBB": {
        "es": "GBB (gas blowback)", "de": "GBB (Gas Blowback)", "fr": "GBB (gas blowback)",
        "it": "GBB (gas blowback)", "pt": "GBB (gas blowback)", "ru": "GBB (газовый блоубэк)",
        "pl": "GBB (gas blowback)", "uk": "GBB (газовий блоубек)", "ro": "GBB (gas blowback)",
        "nl": "GBB (gas blowback)", "hr": "GBB (gas blowback)", "tr": "GBB (gaz geri tepmeli)",
        "hu": "GBB (gas blowback)", "el": "GBB (gas blowback)", "cs": "GBB (gas blowback)",
        "sv": "GBB (gas blowback)", "ca": "GBB (gas blowback)", "bg": "GBB (газов блоубек)",
        "da": "GBB (gas blowback)",
    },
    "gas blowback": {
        "es": "gas blowback", "de": "Gas Blowback", "fr": "gas blowback",
        "it": "gas blowback", "pt": "gas blowback", "ru": "газовый блоубэк",
        "pl": "gas blowback", "uk": "газовий блоубек", "ro": "gas blowback",
        "nl": "gas blowback", "hr": "gas blowback", "tr": "gaz geri tepmeli",
        "hu": "gas blowback", "el": "gas blowback", "cs": "gas blowback",
        "sv": "gas blowback", "ca": "gas blowback", "bg": "газов блоубек",
        "da": "gas blowback",
    },
    "bolt action": {
        "es": "cerrojo", "de": "Repetiergewehr", "fr": "à verrou",
        "it": "a otturatore girevole-scorrevole", "pt": "ferrolho",
        "ru": "болтовой затвор", "pl": "zamek ślizgowo-obrotowy",
        "uk": "болтовий затвор", "ro": "închizător manual",
        "nl": "grendel", "hr": "repetirka", "tr": "sürgülü mekanizma",
        "hu": "tolózáras", "el": "μοχλοκίνητο", "cs": "opakovací závěr",
        "sv": "cylindermekanism", "ca": "forrellat", "bg": "болтово действие",
        "da": "boltmekanisme",
    },
    "sniper rifle": {
        "es": "rifle de francotirador", "de": "Scharfschützengewehr", "fr": "fusil de précision",
        "it": "fucile da cecchino", "pt": "rifle sniper", "ru": "снайперская винтовка",
        "pl": "karabin snajperski", "uk": "снайперська гвинтівка", "ro": "pușcă de lunetist",
        "nl": "sluipschuttersgeweer", "hr": "snajperska puška", "tr": "keskin nişancı tüfeği",
        "hu": "mesterlövész puska", "el": "τυφέκιο ελεύθερου σκοπευτή", "cs": "odstřelovací puška",
        "sv": "prickskyttegevär", "ca": "fusell de franctirador", "bg": "снайперска пушка",
        "da": "sniperriffel",
    },
    "submachine gun": {
        "es": "subfusil", "de": "Maschinenpistole", "fr": "pistolet-mitrailleur",
        "it": "mitra", "pt": "submetralhadora", "ru": "пистолет-пулемёт",
        "pl": "pistolet maszynowy", "uk": "пістолет-кулемет", "ro": "pistol-mitralieră",
        "nl": "machinepistool", "hr": "automat", "tr": "hafif makineli tüfek",
        "hu": "géppisztoly", "el": "υποπολυβόλο", "cs": "samopal",
        "sv": "kulsprutepistol", "ca": "subfusell", "bg": "пистолет-картечница",
        "da": "maskinpistol",
    },
    "shotgun": {
        "es": "escopeta", "de": "Schrotflinte", "fr": "fusil à pompe",
        "it": "fucile a pompa", "pt": "espingarda", "ru": "дробовик",
        "pl": "strzelba", "uk": "дробовик", "ro": "pușcă cu alice",
        "nl": "shotgun", "hr": "sačmarica", "tr": "pompalı tüfek",
        "hu": "sörétes puska", "el": "κυνηγετικό όπλο", "cs": "brokovnice",
        "sv": "hagelgevär", "ca": "escopeta", "bg": "пушка-помпа",
        "da": "haglgevær",
    },
    "grenade launcher": {
        "es": "lanzagranadas", "de": "Granatwerfer", "fr": "lance-grenades",
        "it": "lanciagranate", "pt": "lança-granadas", "ru": "гранатомёт",
        "pl": "granatnik", "uk": "гранатомет", "ro": "lansator de grenade",
        "nl": "granaatwerper", "hr": "bacač granata", "tr": "bomba atar",
        "hu": "gránátvető", "el": "εκτοξευτής χειροβομβίδων", "cs": "granátomet",
        "sv": "granatkastare", "ca": "llançagranades", "bg": "гранатомет",
        "da": "granatkaster",
    },
    "carbine": {
        "es": "carabina", "de": "Karabiner", "fr": "carabine", "it": "carabina",
        "pt": "carabina", "ru": "карабин", "pl": "karabinek", "uk": "карабін",
        "ro": "carabină", "nl": "karabijn", "hr": "karabinka", "tr": "karabina",
        "hu": "karabély", "el": "καραμπίνα", "cs": "karabina", "sv": "karbin",
        "ca": "carabina", "bg": "карабина", "da": "karabin",
    },

    # ══════════════════════════════════════════════════════════════
    # PROPULSION / POWER
    # ══════════════════════════════════════════════════════════════

    "blowback": {
        "es": "blowback", "de": "Blowback", "fr": "blowback", "it": "blowback",
        "pt": "blowback", "ru": "блоубэк", "pl": "blowback", "uk": "блоубек",
        "ro": "blowback", "nl": "blowback", "hr": "blowback", "tr": "geri tepme",
        "hu": "blowback", "el": "blowback", "cs": "blowback", "sv": "blowback",
        "ca": "blowback", "bg": "блоубек", "da": "blowback",
    },
    "recoil": {
        "es": "retroceso", "de": "Rückstoß", "fr": "recul", "it": "rinculo",
        "pt": "recuo", "ru": "отдача", "pl": "odrzut", "uk": "віддача",
        "ro": "recul", "nl": "terugslag", "hr": "trzaj", "tr": "geri tepme",
        "hu": "hátralökés", "el": "ανάκρουση", "cs": "zpětný ráz", "sv": "rekyl",
        "ca": "retrocés", "bg": "откат", "da": "rekyl",
    },
    "green gas": {
        "es": "green gas", "de": "Green Gas", "fr": "green gas", "it": "green gas",
        "pt": "green gas", "ru": "грин газ", "pl": "green gas", "uk": "грін газ",
        "ro": "green gas", "nl": "green gas", "hr": "green gas", "tr": "green gas",
        "hu": "green gas", "el": "green gas", "cs": "green gas", "sv": "green gas",
        "ca": "green gas", "bg": "грийн газ", "da": "green gas",
    },
    "battery": {
        "es": "batería", "de": "Akku", "fr": "batterie", "it": "batteria",
        "pt": "bateria", "ru": "аккумулятор", "pl": "akumulator", "uk": "акумулятор",
        "ro": "baterie", "nl": "accu", "hr": "baterija", "tr": "batarya",
        "hu": "akkumulátor", "el": "μπαταρία", "cs": "baterie", "sv": "batteri",
        "ca": "bateria", "bg": "батерия", "da": "batteri",
    },
    "charger": {
        "es": "cargador de batería", "de": "Ladegerät", "fr": "chargeur de batterie",
        "it": "caricabatterie", "pt": "carregador de bateria", "ru": "зарядное устройство",
        "pl": "ładowarka", "uk": "зарядний пристрій", "ro": "încărcător de baterie",
        "nl": "lader", "hr": "punjač", "tr": "şarj cihazı",
        "hu": "töltő", "el": "φορτιστής", "cs": "nabíječka", "sv": "laddare",
        "ca": "carregador de bateria", "bg": "зарядно устройство", "da": "oplader",
    },
    "MOSFET": {
        "es": "MOSFET", "de": "MOSFET", "fr": "MOSFET", "it": "MOSFET",
        "pt": "MOSFET", "ru": "MOSFET", "pl": "MOSFET", "uk": "MOSFET",
        "ro": "MOSFET", "nl": "MOSFET", "hr": "MOSFET", "tr": "MOSFET",
        "hu": "MOSFET", "el": "MOSFET", "cs": "MOSFET", "sv": "MOSFET",
        "ca": "MOSFET", "bg": "MOSFET", "da": "MOSFET",
    },
    "rate of fire": {
        "es": "cadencia de tiro", "de": "Feuerrate", "fr": "cadence de tir",
        "it": "cadenza di tiro", "pt": "cadência de tiro", "ru": "скорострельность",
        "pl": "szybkostrzelność", "uk": "швидкострільність", "ro": "cadența de tragere",
        "nl": "vuursnelheid", "hr": "brzina paljbe", "tr": "atış hızı",
        "hu": "tűzgyorsaság", "el": "ρυθμός βολής", "cs": "kadence palby",
        "sv": "eldhastighet", "ca": "cadència de tir", "bg": "скорост на стрелба",
        "da": "skudhastighed",
    },
    "muzzle velocity": {
        "es": "velocidad de boca", "de": "Mündungsgeschwindigkeit", "fr": "vitesse à la bouche",
        "it": "velocità alla bocca", "pt": "velocidade de saída", "ru": "дульная скорость",
        "pl": "prędkość wylotowa", "uk": "дульна швидкість", "ro": "viteza la gură",
        "nl": "mondingssnelheid", "hr": "brzina izlaza", "tr": "namlu hızı",
        "hu": "csőtorkolati sebesség", "el": "ταχύτητα στομίου", "cs": "úsťová rychlost",
        "sv": "mynningshastighet", "ca": "velocitat de boca", "bg": "дулна скорост",
        "da": "mundingshastighed",
    },

    # ══════════════════════════════════════════════════════════════
    # AMMUNITION
    # ══════════════════════════════════════════════════════════════

    "BB": {
        "es": "BB", "de": "BB", "fr": "BB", "it": "BB", "pt": "BB",
        "ru": "шар", "pl": "kulka", "uk": "кулька", "ro": "BB",
        "nl": "BB", "hr": "kuglica", "tr": "BB", "hu": "BB",
        "el": "BB", "cs": "BB", "sv": "BB", "ca": "BB", "bg": "BB", "da": "BB",
    },
    "BBs": {
        "es": "BBs", "de": "BBs", "fr": "BBs", "it": "BBs", "pt": "BBs",
        "ru": "шары", "pl": "kulki", "uk": "кульки", "ro": "BBs",
        "nl": "BBs", "hr": "kuglice", "tr": "BBler", "hu": "BBk",
        "el": "BBs", "cs": "BBčka", "sv": "BBs", "ca": "BBs", "bg": "BBта", "da": "BBs",
    },
    "biodegradable BBs": {
        "es": "BBs biodegradables", "de": "biologisch abbaubare BBs",
        "fr": "BBs biodégradables", "it": "BBs biodegradabili",
        "pt": "BBs biodegradáveis", "ru": "биоразлагаемые шары",
        "pl": "kulki biodegradowalne", "uk": "біорозкладні кульки",
        "ro": "BBs biodegradabile", "nl": "biologisch afbreekbare BBs",
        "hr": "biorazgradive kuglice", "tr": "biyobozunur BBler",
        "hu": "biológiailag lebomló BBk", "el": "βιοαποδομήσιμα BBs",
        "cs": "biologicky rozložitelná BBčka", "sv": "bionedbrytbara BBs",
        "ca": "BBs biodegradables", "bg": "биоразградими BBта",
        "da": "bionedbrydelige BBs",
    },
    "tracer BBs": {
        "es": "BBs trazadoras", "de": "Tracer BBs", "fr": "BBs traçantes",
        "it": "BBs traccianti", "pt": "BBs traçantes", "ru": "трассирующие шары",
        "pl": "kulki smugowe", "uk": "трасуючі кульки", "ro": "BBs trasoare",
        "nl": "tracer BBs", "hr": "tracer kuglice", "tr": "izleyici BBler",
        "hu": "fényjeles BBk", "el": "ιχνηθετικά BBs", "cs": "tracer BBčka",
        "sv": "tracer BBs", "ca": "BBs traçadores", "bg": "трасиращи BBта",
        "da": "tracer BBs",
    },

    # ══════════════════════════════════════════════════════════════
    # OPTICS & ACCESSORIES
    # ══════════════════════════════════════════════════════════════

    "red dot sight": {
        "es": "visor de punto rojo", "de": "Rotpunktvisier", "fr": "viseur point rouge",
        "it": "mirino punto rosso", "pt": "mira de ponto vermelho", "ru": "коллиматорный прицел",
        "pl": "celownik kolimatorowy", "uk": "коліматорний приціл", "ro": "punct roșu",
        "nl": "rood punt vizier", "hr": "crvena točka", "tr": "kırmızı nokta nişangah",
        "hu": "red dot irányzék", "el": "κόκκινη κουκκίδα", "cs": "kolimátor",
        "sv": "rödpunktssikte", "ca": "visor de punt vermell", "bg": "червена точка",
        "da": "rødpunktsigte",
    },
    "holographic sight": {
        "es": "visor holográfico", "de": "holographisches Visier", "fr": "viseur holographique",
        "it": "mirino olografico", "pt": "mira holográfica", "ru": "голографический прицел",
        "pl": "celownik holograficzny", "uk": "голографічний приціл", "ro": "vizor holographic",
        "nl": "holografisch vizier", "hr": "holografski nišan", "tr": "holografik nişangah",
        "hu": "holografikus irányzék", "el": "ολογραφικό σκοπευτικό", "cs": "holografický zaměřovač",
        "sv": "holografiskt sikte", "ca": "visor hologràfic", "bg": "холографичен прицел",
        "da": "holografisk sigte",
    },
    "scope": {
        "es": "mira telescópica", "de": "Zielfernrohr", "fr": "lunette de visée",
        "it": "cannocchiale", "pt": "luneta", "ru": "оптический прицел",
        "pl": "luneta", "uk": "оптичний приціл", "ro": "lunetă",
        "nl": "richtkijker", "hr": "optički nišan", "tr": "dürbün",
        "hu": "távcső", "el": "τηλεσκοπικό σκοπευτικό", "cs": "puškohled",
        "sv": "kikarsikte", "ca": "mira telescòpica", "bg": "оптичен прицел",
        "da": "kikkertsigte",
    },
    "iron sights": {
        "es": "miras metálicas", "de": "Kimme und Korn", "fr": "organes de visée",
        "it": "mire metalliche", "pt": "miras de ferro", "ru": "механический прицел",
        "pl": "przyrządy celownicze", "uk": "механічний приціл", "ro": "puncte de ochire",
        "nl": "ijzeren vizier", "hr": "mehanički nišan", "tr": "mekanik nişangah",
        "hu": "mechanikus irányzék", "el": "μεταλλικά σκοπευτικά", "cs": "mechanické mířidla",
        "sv": "mekaniskt sikte", "ca": "mires metàl·liques", "bg": "механичен прицел",
        "da": "mekanisk sigte",
    },
    "flashlight": {
        "es": "linterna táctica", "de": "taktische Taschenlampe", "fr": "lampe tactique",
        "it": "torcia tattica", "pt": "lanterna tática", "ru": "тактический фонарь",
        "pl": "latarka taktyczna", "uk": "тактичний ліхтар", "ro": "lanternă tactică",
        "nl": "tactische zaklamp", "hr": "taktička svjetiljka", "tr": "taktik el feneri",
        "hu": "taktikai lámpa", "el": "τακτικός φακός", "cs": "taktická svítilna",
        "sv": "taktisk ficklampa", "ca": "llanterna tàctica", "bg": "тактическо фенерче",
        "da": "taktisk lommelygte",
    },

    # ══════════════════════════════════════════════════════════════
    # TACTICAL GEAR
    # ══════════════════════════════════════════════════════════════

    "plate carrier": {
        "es": "portaplacas", "de": "Plattenträger", "fr": "porte-plaques",
        "it": "plate carrier", "pt": "colete porta-placas", "ru": "плитоноска",
        "pl": "kamizelka na płyty", "uk": "плитоноска", "ro": "port-plăci",
        "nl": "plaatdrager", "hr": "nosač ploča", "tr": "plaka taşıyıcı",
        "hu": "lemezviselő", "el": "φορέας πλακών", "cs": "nosič plátů",
        "sv": "platbärare", "ca": "portaplaques", "bg": "плейт кериър",
        "da": "pladebærer",
    },
    "tactical vest": {
        "es": "chaleco táctico", "de": "taktische Weste", "fr": "gilet tactique",
        "it": "gilet tattico", "pt": "colete tático", "ru": "тактический жилет",
        "pl": "kamizelka taktyczna", "uk": "тактичний жилет", "ro": "vestă tactică",
        "nl": "tactisch vest", "hr": "taktički prsluk", "tr": "taktik yelek",
        "hu": "taktikai mellény", "el": "τακτικό γιλέκο", "cs": "taktická vesta",
        "sv": "taktisk väst", "ca": "armilla tàctica", "bg": "тактическа жилетка",
        "da": "taktisk vest",
    },
    "magazine pouch": {
        "es": "portacargador", "de": "Magazintasche", "fr": "porte-chargeur",
        "it": "porta caricatore", "pt": "porta-carregador", "ru": "подсумок для магазинов",
        "pl": "ładownica", "uk": "підсумок для магазинів", "ro": "buzunar pentru încărcător",
        "nl": "magazijntas", "hr": "futrola za spremnike", "tr": "şarjör cebi",
        "hu": "tártáska", "el": "θήκη γεμιστήρα", "cs": "sumka na zásobníky",
        "sv": "magasinficka", "ca": "portacarregador", "bg": "джоб за пълнители",
        "da": "magasinlomme",
    },
    "holster": {
        "es": "funda", "de": "Holster", "fr": "holster", "it": "fondina",
        "pt": "coldre", "ru": "кобура", "pl": "kabura", "uk": "кобура",
        "ro": "toc", "nl": "holster", "hr": "futrola", "tr": "kılıf",
        "hu": "pisztolytáska", "el": "θήκη πιστολιού", "cs": "pouzdro", "sv": "hölster",
        "ca": "funda", "bg": "кобур", "da": "hylster",
    },
    "helmet": {
        "es": "casco", "de": "Helm", "fr": "casque", "it": "elmetto",
        "pt": "capacete", "ru": "шлем", "pl": "hełm", "uk": "шолом",
        "ro": "cască", "nl": "helm", "hr": "kaciga", "tr": "kask",
        "hu": "sisak", "el": "κράνος", "cs": "helma", "sv": "hjälm",
        "ca": "casc", "bg": "шлем", "da": "hjelm",
    },

    # ══════════════════════════════════════════════════════════════
    # PROTECTION
    # ══════════════════════════════════════════════════════════════

    "goggles": {
        "es": "gafas de protección", "de": "Schutzbrille", "fr": "lunettes de protection",
        "it": "occhiali protettivi", "pt": "óculos de proteção", "ru": "защитные очки",
        "pl": "gogle ochronne", "uk": "захисні окуляри", "ro": "ochelari de protecție",
        "nl": "beschermbril", "hr": "zaštitne naočale", "tr": "koruyucu gözlük",
        "hu": "védőszemüveg", "el": "προστατευτικά γυαλιά", "cs": "ochranné brýle",
        "sv": "skyddsglasögon", "ca": "ulleres de protecció", "bg": "предпазни очила",
        "da": "beskyttelsesbriller",
    },
    "full face mask": {
        "es": "máscara facial completa", "de": "Vollgesichtsmaske", "fr": "masque intégral",
        "it": "maschera integrale", "pt": "máscara facial completa",
        "ru": "полнолицевая маска", "pl": "maska pełna",
        "uk": "повнолицева маска", "ro": "mască integrală",
        "nl": "volledig gezichtsmasker", "hr": "puna maska za lice",
        "tr": "tam yüz maskesi", "hu": "teljes arcvédő maszk",
        "el": "μάσκα πλήρους προσώπου", "cs": "celoobličejová maska",
        "sv": "heltäckande ansiktsmask", "ca": "màscara facial completa",
        "bg": "маска за цялото лице", "da": "heldækkende ansigtsmaske",
    },
    "mesh mask": {
        "es": "máscara de malla", "de": "Gittermaske", "fr": "masque en grillage",
        "it": "maschera a rete", "pt": "máscara de malha", "ru": "сетчатая маска",
        "pl": "maska siatkowa", "uk": "сітчаста маска", "ro": "mască de plasă",
        "nl": "gaasmasker", "hr": "mrežasta maska", "tr": "ağ maske",
        "hu": "hálós maszk", "el": "μάσκα πλέγματος", "cs": "síťovaná maska",
        "sv": "nätmask", "ca": "màscara de malla", "bg": "мрежеста маска",
        "da": "netmaske",
    },
    "eye protection": {
        "es": "protección ocular", "de": "Augenschutz", "fr": "protection oculaire",
        "it": "protezione oculare", "pt": "proteção ocular", "ru": "защита глаз",
        "pl": "ochrona oczu", "uk": "захист очей", "ro": "protecție oculară",
        "nl": "oogbescherming", "hr": "zaštita očiju", "tr": "göz koruması",
        "hu": "szemvédelem", "el": "προστασία ματιών", "cs": "ochrana očí",
        "sv": "ögonskydd", "ca": "protecció ocular", "bg": "защита за очите",
        "da": "øjenbeskyttelse",
    },

    # ══════════════════════════════════════════════════════════════
    # GAMEPLAY
    # ══════════════════════════════════════════════════════════════

    "CQB": {
        "es": "CQB (combate en espacios cerrados)", "de": "CQB (Nahkampf)",
        "fr": "CQB (combat rapproché)", "it": "CQB (combattimento ravvicinato)",
        "pt": "CQB (combate em espaço confinado)", "ru": "CQB (ближний бой)",
        "pl": "CQB (walka w zamkniętych pomieszczeniach)", "uk": "CQB (ближній бій)",
        "ro": "CQB (luptă la distanță mică)", "nl": "CQB (korte afstand gevecht)",
        "hr": "CQB (borba u zatvorenom)", "tr": "CQB (yakın muharebe)",
        "hu": "CQB (közelharc)", "el": "CQB (μάχη σε κλειστό χώρο)",
        "cs": "CQB (boj zblízka)", "sv": "CQB (närstrid)",
        "ca": "CQB (combat en espais tancats)", "bg": "CQB (бой в сграда)",
        "da": "CQB (nærkamp)",
    },
    "milsim": {
        "es": "milsim (simulación militar)", "de": "MilSim (Militärsimulation)",
        "fr": "milsim (simulation militaire)", "it": "milsim (simulazione militare)",
        "pt": "milsim (simulação militar)", "ru": "милсим (военная симуляция)",
        "pl": "milsim (symulacja wojskowa)", "uk": "мілсім (військова симуляція)",
        "ro": "milsim (simulare militară)", "nl": "milsim (militaire simulatie)",
        "hr": "milsim (vojna simulacija)", "tr": "milsim (askeri simülasyon)",
        "hu": "milsim (katonai szimuláció)", "el": "milsim (στρατιωτική προσομοίωση)",
        "cs": "milsim (vojenská simulace)", "sv": "milsim (militär simulering)",
        "ca": "milsim (simulació militar)", "bg": "милсим (военна симулация)",
        "da": "milsim (militær simulering)",
    },
    "skirmish": {
        "es": "partida", "de": "Gefecht", "fr": "partie", "it": "partita",
        "pt": "partida", "ru": "игра", "pl": "gra", "uk": "гра",
        "ro": "partidă", "nl": "gevecht", "hr": "borba", "tr": "çatışma",
        "hu": "játék", "el": "παιχνίδι", "cs": "hra", "sv": "strid",
        "ca": "partida", "bg": "игра", "da": "kamp",
    },
    "chronograph": {
        "es": "cronógrafo", "de": "Chronograph", "fr": "chronographe",
        "it": "cronografo", "pt": "cronógrafo", "ru": "хронограф",
        "pl": "chronograf", "uk": "хронограф", "ro": "cronograf",
        "nl": "chronograaf", "hr": "kronograf", "tr": "kronograf",
        "hu": "kronográf", "el": "χρονογράφος", "cs": "chronograf",
        "sv": "kronograf", "ca": "cronògraf", "bg": "хронограф",
        "da": "kronograf",
    },
    "semi-auto": {
        "es": "semiautomático", "de": "halbautomatisch", "fr": "semi-automatique",
        "it": "semiautomatico", "pt": "semiautomático", "ru": "полуавтоматический",
        "pl": "półautomatyczny", "uk": "напівавтоматичний", "ro": "semiautomat",
        "nl": "halfautomatisch", "hr": "poluautomatski", "tr": "yarı otomatik",
        "hu": "félautomata", "el": "ημιαυτόματο", "cs": "poloautomatický",
        "sv": "halvautomatisk", "ca": "semiautomàtic", "bg": "полуавтоматичен",
        "da": "halvautomatisk",
    },
    "full-auto": {
        "es": "automático", "de": "vollautomatisch", "fr": "automatique",
        "it": "automatico", "pt": "automático", "ru": "автоматический",
        "pl": "automatyczny", "uk": "автоматичний", "ro": "automat",
        "nl": "volautomatisch", "hr": "automatski", "tr": "tam otomatik",
        "hu": "automata", "el": "αυτόματο", "cs": "automatický",
        "sv": "helautomatisk", "ca": "automàtic", "bg": "автоматичен",
        "da": "fuldautomatisk",
    },

    # ══════════════════════════════════════════════════════════════
    # MATERIALS
    # ══════════════════════════════════════════════════════════════

    "full metal": {
        "es": "full metal", "de": "Vollmetall", "fr": "full métal",
        "it": "full metal", "pt": "full metal", "ru": "фулл метал",
        "pl": "full metal", "uk": "фулл метал", "ro": "full metal",
        "nl": "full metal", "hr": "full metal", "tr": "tam metal",
        "hu": "full metal", "el": "full metal", "cs": "full metal",
        "sv": "full metal", "ca": "full metal", "bg": "фул метал",
        "da": "fuld metal",
    },
    "polymer": {
        "es": "polímero", "de": "Polymer", "fr": "polymère", "it": "polimero",
        "pt": "polímero", "ru": "полимер", "pl": "polimer", "uk": "полімер",
        "ro": "polimer", "nl": "polymeer", "hr": "polimer", "tr": "polimer",
        "hu": "polimer", "el": "πολυμερές", "cs": "polymer", "sv": "polymer",
        "ca": "polímer", "bg": "полимер", "da": "polymer",
    },
    "steel": {
        "es": "acero", "de": "Stahl", "fr": "acier", "it": "acciaio",
        "pt": "aço", "ru": "сталь", "pl": "stal", "uk": "сталь",
        "ro": "oțel", "nl": "staal", "hr": "čelik", "tr": "çelik",
        "hu": "acél", "el": "ατσάλι", "cs": "ocel", "sv": "stål",
        "ca": "acer", "bg": "стомана", "da": "stål",
    },
    "aluminum alloy": {
        "es": "aleación de aluminio", "de": "Aluminiumlegierung", "fr": "alliage d'aluminium",
        "it": "lega di alluminio", "pt": "liga de alumínio", "ru": "алюминиевый сплав",
        "pl": "stop aluminium", "uk": "алюмінієвий сплав", "ro": "aliaj de aluminiu",
        "nl": "aluminiumlegering", "hr": "aluminijska legura", "tr": "alüminyum alaşım",
        "hu": "alumíniumötvözet", "el": "κράμα αλουμινίου", "cs": "hliníková slitina",
        "sv": "aluminiumlegering", "ca": "aliatge d'alumini", "bg": "алуминиева сплав",
        "da": "aluminiumslegering",
    },

    # ══════════════════════════════════════════════════════════════
    # UPGRADES & INTERNALS
    # ══════════════════════════════════════════════════════════════

    "upgrade": {
        "es": "mejora", "de": "Upgrade", "fr": "amélioration", "it": "potenziamento",
        "pt": "melhoria", "ru": "апгрейд", "pl": "ulepszenie", "uk": "апгрейд",
        "ro": "îmbunătățire", "nl": "upgrade", "hr": "nadogradnja", "tr": "yükseltme",
        "hu": "fejlesztés", "el": "αναβάθμιση", "cs": "vylepšení", "sv": "uppgradering",
        "ca": "millora", "bg": "ъпгрейд", "da": "opgradering",
    },
    "tight bore barrel": {
        "es": "cañón de precisión", "de": "Präzisionslauf", "fr": "canon de précision",
        "it": "canna di precisione", "pt": "cano de precisão", "ru": "прецизионный ствол",
        "pl": "lufa precyzyjna", "uk": "прецизійний стовбур", "ro": "țeavă de precizie",
        "nl": "precisieloop", "hr": "precizna cijev", "tr": "hassas namlu",
        "hu": "precíziós cső", "el": "κάννη ακριβείας", "cs": "přesná hlaveň",
        "sv": "precisionspipa", "ca": "canó de precisió", "bg": "прецизен ствол",
        "da": "præcisionsløb",
    },
    "precision barrel": {
        "es": "cañón de precisión", "de": "Präzisionslauf", "fr": "canon de précision",
        "it": "canna di precisione", "pt": "cano de precisão", "ru": "прецизионный ствол",
        "pl": "lufa precyzyjna", "uk": "прецизійний стовбур", "ro": "țeavă de precizie",
        "nl": "precisieloop", "hr": "precizna cijev", "tr": "hassas namlu",
        "hu": "precíziós cső", "el": "κάννη ακριβείας", "cs": "přesná hlaveň",
        "sv": "precisionspipa", "ca": "canó de precisió", "bg": "прецизен ствол",
        "da": "præcisionsløb",
    },
    "motor": {
        "es": "motor", "de": "Motor", "fr": "moteur", "it": "motore",
        "pt": "motor", "ru": "мотор", "pl": "silnik", "uk": "мотор",
        "ro": "motor", "nl": "motor", "hr": "motor", "tr": "motor",
        "hu": "motor", "el": "κινητήρας", "cs": "motor", "sv": "motor",
        "ca": "motor", "bg": "мотор", "da": "motor",
    },
    "gear set": {
        "es": "set de engranajes", "de": "Zahnradsatz", "fr": "jeu d'engrenages",
        "it": "set ingranaggi", "pt": "conjunto de engrenagens", "ru": "набор шестерён",
        "pl": "zestaw kół zębatych", "uk": "набір шестерень", "ro": "set de angrenaje",
        "nl": "tandwielset", "hr": "set zupčanika", "tr": "dişli seti",
        "hu": "fogaskerék készlet", "el": "σετ γραναζιών", "cs": "sada ozubených kol",
        "sv": "kugghjulsset", "ca": "joc d'engranatges", "bg": "комплект зъбни колела",
        "da": "tandhjulssæt",
    },
    "wiring": {
        "es": "cableado", "de": "Verkabelung", "fr": "câblage", "it": "cablaggio",
        "pt": "fiação", "ru": "проводка", "pl": "okablowanie", "uk": "проводка",
        "ro": "cablaj", "nl": "bedrading", "hr": "kabliranje", "tr": "kablolama",
        "hu": "kábelezés", "el": "καλωδίωση", "cs": "kabeláž", "sv": "kabeldragning",
        "ca": "cablejat", "bg": "окабеляване", "da": "ledningsføring",
    },
}


# ── Supported languages ────────────────────────────────────────

SUPPORTED_LANGUAGES = {
    "en": "English",
    "es": "Spanish",
    "de": "German",
    "fr": "French",
    "it": "Italian",
    "pt": "Portuguese",
    "ru": "Russian",
    "pl": "Polish",
    "uk": "Ukrainian",
    "ro": "Romanian",
    "nl": "Dutch",
    "hr": "Serbo-Croatian",
    "tr": "Turkish",
    "hu": "Hungarian",
    "el": "Greek",
    "cs": "Czech",
    "sv": "Swedish",
    "ca": "Catalan",
    "bg": "Bulgarian",
    "da": "Danish",
}


def get_glossary_for_pair(source_lang: str, target_lang: str) -> dict:
    """Get glossary dict for a specific language pair.

    Uses English as the hub language:
    - EN→XX: returns {en_term: xx_translation}
    - XX→EN: returns {xx_translation: en_term}
    - XX→YY: returns {xx_translation: yy_translation} (via English hub)
    """
    result = {}

    if source_lang == "en":
        # EN→target: straightforward
        for en_term, translations in GLOSSARY.items():
            if target_lang in translations:
                result[en_term.lower()] = translations[target_lang]
    elif target_lang == "en":
        # source→EN: reverse lookup
        for en_term, translations in GLOSSARY.items():
            if source_lang in translations:
                result[translations[source_lang].lower()] = en_term
    else:
        # XX→YY: go through English hub
        for en_term, translations in GLOSSARY.items():
            if source_lang in translations and target_lang in translations:
                result[translations[source_lang].lower()] = translations[target_lang]

    return result
