"""
Multi-language airsoft terminology glossary.

Structure: EN term (lowercase) -> {lang_code: translation}
English is the hub language — all lookups go through EN keys.

Languages supported:
  es (Spanish), de (German), fr (French), it (Italian), pt (Portuguese),
  ru (Russian), pl (Polish), uk (Ukrainian), ro (Romanian), nl (Dutch),
  hr (Serbo-Croatian), tr (Turkish), hu (Hungarian), el (Greek),
  cs (Czech), sv (Swedish), ca (Catalan), bg (Bulgarian), da (Danish),
  zh (Chinese), ja (Japanese)
"""

GLOSSARY = {
    # ══════════════════════════════════════════════════════════════
    # WEAPON PARTS
    # ══════════════════════════════════════════════════════════════

    "inner barrel": {
        "es": "cañón interior",
        "de": "Innenlauf",
        "fr": "canon interne",
        "it": "canna interna",
        "pt": "cano interno",
        "ru": "внутренний ствол",
        "pl": "lufa wewnętrzna",
        "uk": "внутрішній стовбур",
        "ro": "țeavă interioară",
        "nl": "binnenloop",
        "hr": "unutarnja cijev",
        "tr": "iç namlu",
        "hu": "belső cső",
        "el": "εσωτερική κάννη",
        "cs": "vnitřní hlaveň",
        "sv": "innerpipa",
        "ca": "canó interior",
        "bg": "вътрешен ствол",
        "da": "indre løb",
        "zh": "内管", "ja": "インナーバレル",
    },
    "outer barrel": {
        "es": "cañón exterior",
        "de": "Außenlauf",
        "fr": "canon externe",
        "it": "canna esterna",
        "pt": "cano externo",
        "ru": "внешний ствол",
        "pl": "lufa zewnętrzna",
        "uk": "зовнішній стовбур",
        "ro": "țeavă exterioară",
        "nl": "buitenloop",
        "hr": "vanjska cijev",
        "tr": "dış namlu",
        "hu": "külső cső",
        "el": "εξωτερική κάννη",
        "cs": "vnější hlaveň",
        "sv": "ytterpipa",
        "ca": "canó exterior",
        "bg": "външен ствол",
        "da": "ydre løb",
        "zh": "外管", "ja": "アウターバレル",
    },
    "barrel": {
        "es": "cañón",
        "de": "Lauf",
        "fr": "canon",
        "it": "canna",
        "pt": "cano",
        "ru": "ствол",
        "pl": "lufa",
        "uk": "стовбур",
        "ro": "țeavă",
        "nl": "loop",
        "hr": "cijev",
        "tr": "namlu",
        "hu": "cső",
        "el": "κάννη",
        "cs": "hlaveň",
        "sv": "pipa",
        "ca": "canó",
        "bg": "ствол",
        "da": "løb",
        "zh": "枪管", "ja": "バレル",
    },
    "barrel extension": {
        "es": "extensión de cañón",
        "de": "Laufverlängerung",
        "fr": "extension de canon",
        "it": "estensione canna",
        "pt": "extensão de cano",
        "ru": "удлинитель ствола",
        "pl": "przedłużka lufy",
        "uk": "подовжувач стовбура",
        "ro": "extensie de țeavă",
        "nl": "loopverlenging",
        "hr": "produžetak cijevi",
        "tr": "namlu uzatması",
        "hu": "csőhosszabbító",
        "el": "προέκταση κάννης",
        "cs": "prodloužení hlavně",
        "sv": "pipförlängare",
        "ca": "extensió de canó",
        "bg": "удължител на ствола",
        "da": "løbforlænger",
        "zh": "枪管延长件", "ja": "バレルエクステンション",
    },
    "barrel length": {
        "es": "longitud de cañón",
        "de": "Lauflänge",
        "fr": "longueur de canon",
        "it": "lunghezza canna",
        "pt": "comprimento do cano",
        "ru": "длина ствола",
        "pl": "długość lufy",
        "uk": "довжина стовбура",
        "ro": "lungimea țevii",
        "nl": "looplengte",
        "hr": "duljina cijevi",
        "tr": "namlu uzunluğu",
        "hu": "csőhossz",
        "el": "μήκος κάννης",
        "cs": "délka hlavně",
        "sv": "piplängd",
        "ca": "longitud del canó",
        "bg": "дължина на ствола",
        "da": "løblængde",
        "zh": "枪管长度", "ja": "バレル長",
    },
    "hop-up": {
        "es": "hop-up", "de": "Hop-Up", "fr": "hop-up", "it": "hop-up",
        "pt": "hop-up", "ru": "хоп-ап", "pl": "hop-up", "uk": "хоп-ап",
        "ro": "hop-up", "nl": "hop-up", "hr": "hop-up", "tr": "hop-up",
        "hu": "hop-up", "el": "hop-up", "cs": "hop-up", "sv": "hop-up",
        "ca": "hop-up", "bg": "хоп-ъп", "da": "hop-up",
        "zh": "hop-up", "ja": "ホップアップ",
    },
    "hop-up chamber": {
        "es": "cámara de hop-up",
        "de": "Hop-Up-Kammer",
        "fr": "chambre de hop-up",
        "it": "camera hop-up",
        "pt": "câmara de hop-up",
        "ru": "камера хоп-апа",
        "pl": "komora hop-up",
        "uk": "камера хоп-апу",
        "ro": "cameră hop-up",
        "nl": "hop-up kamer",
        "hr": "hop-up komora",
        "tr": "hop-up haznesi",
        "hu": "hop-up kamra",
        "el": "θάλαμος hop-up",
        "cs": "hop-up komora",
        "sv": "hop-up-kammare",
        "ca": "cambra de hop-up",
        "bg": "камера на хоп-ъп",
        "da": "hop-up kammer",
        "zh": "hop-up座", "ja": "ホップアップチャンバー",
    },
    "hop-up bucking": {
        "es": "goma de hop-up",
        "de": "Hop-Up-Gummi",
        "fr": "joint de hop-up",
        "it": "gommino hop-up",
        "pt": "borracha de hop-up",
        "ru": "резинка хоп-апа",
        "pl": "gumka hop-up",
        "uk": "гумка хоп-апу",
        "ro": "cauciuc hop-up",
        "nl": "hop-up rubber",
        "hr": "hop-up gumica",
        "tr": "hop-up lastiği",
        "hu": "hop-up gumi",
        "el": "λάστιχο hop-up",
        "cs": "hop-up gumička",
        "sv": "hop-up-gummi",
        "ca": "goma de hop-up",
        "bg": "гумичка за хоп-ъп",
        "da": "hop-up gummi",
        "zh": "hop-up胶皮", "ja": "ホップアップパッキン",
    },
    "hop-up nub": {
        "es": "nub de hop-up", "de": "Hop-Up-Nub", "fr": "nub de hop-up",
        "it": "nub hop-up", "pt": "nub de hop-up", "ru": "наб хоп-апа",
        "pl": "nub hop-up", "uk": "наб хоп-апу", "ro": "nub hop-up",
        "nl": "hop-up nub", "hr": "hop-up nub", "tr": "hop-up nub",
        "hu": "hop-up nub", "el": "nub hop-up", "cs": "hop-up nub",
        "sv": "hop-up-nub", "ca": "nub de hop-up", "bg": "наб за хоп-ъп",
        "da": "hop-up nub",
        "zh": "hop-up压点", "ja": "ホップアップナブ",
    },
    "gearbox": {
        "es": "gearbox", "de": "Gearbox", "fr": "gearbox", "it": "gearbox",
        "pt": "gearbox", "ru": "гирбокс", "pl": "gearbox", "uk": "гірбокс",
        "ro": "gearbox", "nl": "gearbox", "hr": "gearbox", "tr": "gearbox",
        "hu": "gearbox", "el": "gearbox", "cs": "gearbox", "sv": "gearbox",
        "ca": "gearbox", "bg": "гиърбокс", "da": "gearbox",
        "zh": "齿轮箱", "ja": "ギアボックス",
    },
    "gearbox shell": {
        "es": "carcasa de gearbox",
        "de": "Gearbox-Gehäuse",
        "fr": "coque de gearbox",
        "it": "guscio gearbox",
        "pt": "carcaça de gearbox",
        "ru": "корпус гирбокса",
        "pl": "szkielet gearboxa",
        "uk": "корпус гірбоксу",
        "ro": "carcasă gearbox",
        "nl": "gearbox behuizing",
        "hr": "kućište gearboxa",
        "tr": "gearbox gövdesi",
        "hu": "gearbox ház",
        "el": "κέλυφος gearbox",
        "cs": "tělo gearboxu",
        "sv": "gearbox-skal",
        "ca": "carcassa de gearbox",
        "bg": "корпус на гиърбокс",
        "da": "gearbox hus",
        "zh": "齿轮箱壳体", "ja": "ギアボックスシェル",
    },
    "cylinder": {
        "es": "cilindro", "de": "Zylinder", "fr": "cylindre", "it": "cilindro",
        "pt": "cilindro", "ru": "цилиндр", "pl": "cylinder", "uk": "циліндр",
        "ro": "cilindru", "nl": "cilinder", "hr": "cilindar", "tr": "silindir",
        "hu": "henger", "el": "κύλινδρος", "cs": "válec", "sv": "cylinder",
        "ca": "cilindre", "bg": "цилиндър", "da": "cylinder",
        "zh": "气缸", "ja": "シリンダー",
    },
    "cylinder head": {
        "es": "cabeza de cilindro",
        "de": "Zylinderkopf",
        "fr": "tête de cylindre",
        "it": "testa cilindro",
        "pt": "cabeça de cilindro",
        "ru": "голова цилиндра",
        "pl": "głowica cylindra",
        "uk": "голова циліндра",
        "ro": "cap cilindru",
        "nl": "cilinderkop",
        "hr": "glava cilindra",
        "tr": "silindir kafası",
        "hu": "hengerfej",
        "el": "κεφαλή κυλίνδρου",
        "cs": "hlava válce",
        "sv": "cylinderhuvud",
        "ca": "cap de cilindre",
        "bg": "глава на цилиндъра",
        "da": "cylinderhoved",
        "zh": "气缸头", "ja": "シリンダーヘッド",
    },
    "piston": {
        "es": "pistón", "de": "Kolben", "fr": "piston", "it": "pistone",
        "pt": "pistão", "ru": "поршень", "pl": "tłok", "uk": "поршень",
        "ro": "piston", "nl": "zuiger", "hr": "klip", "tr": "piston",
        "hu": "dugattyú", "el": "έμβολο", "cs": "píst", "sv": "kolv",
        "ca": "pistó", "bg": "бутало", "da": "stempel",
        "zh": "活塞", "ja": "ピストン",
    },
    "piston head": {
        "es": "cabeza de pistón",
        "de": "Kolbenkopf",
        "fr": "tête de piston",
        "it": "testa pistone",
        "pt": "cabeça de pistão",
        "ru": "голова поршня",
        "pl": "głowica tłoka",
        "uk": "голова поршня",
        "ro": "cap piston",
        "nl": "zuigerkop",
        "hr": "glava klipa",
        "tr": "piston kafası",
        "hu": "dugattyúfej",
        "el": "κεφαλή εμβόλου",
        "cs": "hlava pístu",
        "sv": "kolvhuvud",
        "ca": "cap de pistó",
        "bg": "глава на буталото",
        "da": "stempelhoved",
        "zh": "活塞头", "ja": "ピストンヘッド",
    },
    "spring": {
        "es": "muelle", "de": "Feder", "fr": "ressort", "it": "molla",
        "pt": "mola", "ru": "пружина", "pl": "sprężyna", "uk": "пружина",
        "ro": "arc", "nl": "veer", "hr": "opruga", "tr": "yay",
        "hu": "rugó", "el": "ελατήριο", "cs": "pružina", "sv": "fjäder",
        "ca": "molla", "bg": "пружина", "da": "fjeder",
        "zh": "弹簧", "ja": "スプリング",
    },
    "spring guide": {
        "es": "guía de muelle",
        "de": "Federführung",
        "fr": "guide de ressort",
        "it": "guida molla",
        "pt": "guia de mola",
        "ru": "направляющая пружины",
        "pl": "prowadnica sprężyny",
        "uk": "напрямна пружини",
        "ro": "ghid de arc",
        "nl": "veergeleider",
        "hr": "vodilica opruge",
        "tr": "yay kılavuzu",
        "hu": "rugóvezető",
        "el": "οδηγός ελατηρίου",
        "cs": "vedení pružiny",
        "sv": "fjäderguide",
        "ca": "guia de molla",
        "bg": "водач на пружина",
        "da": "fjederguide",
        "zh": "弹簧导杆", "ja": "スプリングガイド",
    },
    "nozzle": {
        "es": "nozzle", "de": "Nozzle", "fr": "nozzle", "it": "nozzle",
        "pt": "nozzle", "ru": "ноззл", "pl": "nozzle", "uk": "нозл",
        "ro": "nozzle", "nl": "nozzle", "hr": "nozzle", "tr": "nozzle",
        "hu": "nozzle", "el": "nozzle", "cs": "nozzle", "sv": "nozzle",
        "ca": "nozzle", "bg": "нозъл", "da": "nozzle",
        "zh": "喷嘴", "ja": "ノズル",
    },
    "air nozzle": {
        "es": "nozzle de aire", "de": "Luftdüse", "fr": "nozzle d'air",
        "it": "nozzle aria", "pt": "nozzle de ar", "ru": "воздушная форсунка",
        "pl": "dysza powietrza", "uk": "повітряна форсунка", "ro": "duză de aer",
        "nl": "luchtnozzle", "hr": "zračna mlaznica", "tr": "hava nozulu",
        "hu": "levegő fúvóka", "el": "ακροφύσιο αέρα", "cs": "vzduchová tryska",
        "sv": "luftmunstycke", "ca": "nozzle d'aire", "bg": "въздушна дюза",
        "da": "luftdyse",
        "zh": "气嘴", "ja": "エアノズル",
    },
    "tappet plate": {
        "es": "tappet plate", "de": "Tappet Plate", "fr": "tappet plate",
        "it": "tappet plate", "pt": "tappet plate", "ru": "таппет плейт",
        "pl": "tappet plate", "uk": "таппет плейт", "ro": "tappet plate",
        "nl": "tappet plate", "hr": "tappet plate", "tr": "tappet plate",
        "hu": "tappet plate", "el": "tappet plate", "cs": "tappet plate",
        "sv": "tappet plate", "ca": "tappet plate", "bg": "тапет плейт",
        "da": "tappet plate",
        "zh": "拨片", "ja": "タペットプレート",
    },
    "trigger": {
        "es": "gatillo", "de": "Abzug", "fr": "détente", "it": "grilletto",
        "pt": "gatilho", "ru": "спусковой крючок", "pl": "spust", "uk": "спусковий гачок",
        "ro": "trăgaci", "nl": "trekker", "hr": "okidač", "tr": "tetik",
        "hu": "ravasz", "el": "σκανδάλη", "cs": "spoušť", "sv": "avtryckare",
        "ca": "gallet", "bg": "спусък", "da": "aftrækkker",
        "zh": "扳机", "ja": "トリガー",
    },
    "trigger unit": {
        "es": "unidad de gatillo",
        "de": "Abzugseinheit",
        "fr": "unité de détente",
        "it": "unità grilletto",
        "pt": "unidade de gatilho",
        "ru": "спусковой механизм",
        "pl": "mechanizm spustowy",
        "uk": "спусковий механізм",
        "ro": "mecanism de trăgaci",
        "nl": "trekkermechanisme",
        "hr": "okidačka jedinica",
        "tr": "tetik ünitesi",
        "hu": "elsütő mechanizmus",
        "el": "μηχανισμός σκανδάλης",
        "cs": "spouštěcí mechanismus",
        "sv": "avtryckarenhet",
        "ca": "unitat de gallet",
        "bg": "спусков механизъм",
        "da": "aftrækkerenhed",
        "zh": "扳机组件", "ja": "トリガーユニット",
    },
    "trigger guard": {
        "es": "guardamonte", "de": "Abzugsbügel", "fr": "pontet",
        "it": "ponticello", "pt": "guarda-mato", "ru": "спусковая скоба",
        "pl": "kabłąk spustowy", "uk": "спускова скоба", "ro": "apărătoarea trăgaciului",
        "nl": "trekkerbeugel", "hr": "branik okidača", "tr": "tetik muhafazası",
        "hu": "elsütőbillentyű-kengyel", "el": "προφυλακτήρας σκανδάλης",
        "cs": "lučík spouště", "sv": "avtryckarskydd", "ca": "guardamunt",
        "bg": "спусков предпазител", "da": "aftrækkerbøjle",
        "zh": "扳机护圈", "ja": "トリガーガード",
    },
    "selector plate": {
        "es": "selector de tiro", "de": "Selectorplatte", "fr": "sélecteur de tir",
        "it": "selettore di tiro", "pt": "seletor de tiro", "ru": "селекторная пластина",
        "pl": "płytka selektora", "uk": "селекторна пластина", "ro": "placă selector",
        "nl": "selectorplaat", "hr": "selektor ploča", "tr": "seçici plakası",
        "hu": "szelektor lemez", "el": "πλάκα επιλογέα", "cs": "selectorová destička",
        "sv": "selektorplatta", "ca": "selector de tir", "bg": "селекторна пластина",
        "da": "selectorplade",
        "zh": "快慢机板", "ja": "セレクタープレート",
    },
    "fire selector": {
        "es": "selector de tiro", "de": "Feuermodus-Wähler", "fr": "sélecteur de tir",
        "it": "selettore di tiro", "pt": "seletor de tiro", "ru": "переводчик огня",
        "pl": "przełącznik ognia", "uk": "перемикач вогню", "ro": "selector de foc",
        "nl": "vuurkeuze schakelaar", "hr": "selektor vatre", "tr": "ateş seçici",
        "hu": "tűzváltó", "el": "επιλογέας πυρός", "cs": "přepínač palby",
        "sv": "eldväljare", "ca": "selector de foc", "bg": "превключвател на огъня",
        "da": "ildvælger",
        "zh": "射击选择器", "ja": "セレクターレバー",
    },
    "safety": {
        "es": "seguro", "de": "Sicherung", "fr": "sécurité", "it": "sicura",
        "pt": "trava de segurança", "ru": "предохранитель", "pl": "bezpiecznik",
        "uk": "запобіжник", "ro": "siguranță", "nl": "veiligheidspal",
        "hr": "osigurač", "tr": "emniyet", "hu": "biztosíték",
        "el": "ασφάλεια", "cs": "pojistka", "sv": "säkring",
        "ca": "seguretat", "bg": "предпазител", "da": "sikring",
        "zh": "保险", "ja": "セーフティ",
    },
    "safety lever": {
        "es": "palanca de seguro", "de": "Sicherungshebel", "fr": "levier de sécurité",
        "it": "leva di sicura", "pt": "alavanca de segurança", "ru": "рычаг предохранителя",
        "pl": "dźwignia bezpiecznika", "uk": "важіль запобіжника", "ro": "manetă siguranță",
        "nl": "veiligheidshendel", "hr": "poluga osigurača", "tr": "emniyet kolu",
        "hu": "biztosítókar", "el": "μοχλός ασφαλείας", "cs": "páka pojistky",
        "sv": "säkringsspak", "ca": "palanca de seguretat", "bg": "лост на предпазителя",
        "da": "sikringsgreb",
        "zh": "保险杆", "ja": "セーフティレバー",
    },
    "stock": {
        "es": "culata", "de": "Schaft", "fr": "crosse", "it": "calcio",
        "pt": "coronha", "ru": "приклад", "pl": "kolba", "uk": "приклад",
        "ro": "pat", "nl": "kolf", "hr": "kundak", "tr": "dipçik",
        "hu": "tus", "el": "κοντάκι", "cs": "pažba", "sv": "kolv",
        "ca": "culata", "bg": "приклад", "da": "kolbe",
        "zh": "枪托", "ja": "ストック",
    },
    "folding stock": {
        "es": "culata plegable", "de": "Klappschaft", "fr": "crosse pliante",
        "it": "calcio pieghevole", "pt": "coronha dobrável", "ru": "складной приклад",
        "pl": "kolba składana", "uk": "складний приклад", "ro": "pat pliabil",
        "nl": "opvouwbare kolf", "hr": "sklopivi kundak", "tr": "katlanır dipçik",
        "hu": "összehajtható tus", "el": "αναδιπλούμενο κοντάκι", "cs": "sklopná pažba",
        "sv": "fällbar kolv", "ca": "culata plegable", "bg": "сгъваем приклад",
        "da": "foldbar kolbe",
        "zh": "折叠枪托", "ja": "フォールディングストック",
    },
    "retractable stock": {
        "es": "culata retráctil", "de": "Schiebeschaft", "fr": "crosse rétractable",
        "it": "calcio retraibile", "pt": "coronha retrátil", "ru": "выдвижной приклад",
        "pl": "kolba wysuwana", "uk": "висувний приклад", "ro": "pat retractabil",
        "nl": "intrekbare kolf", "hr": "uvlačivi kundak", "tr": "geri çekilebilir dipçik",
        "hu": "behúzható tus", "el": "ανασυρόμενο κοντάκι", "cs": "zasouvací pažba",
        "sv": "utdragbar kolv", "ca": "culata retràctil", "bg": "прибиращ се приклад",
        "da": "udtrækkelig kolbe",
        "zh": "伸缩枪托", "ja": "リトラクタブルストック",
    },
    "adjustable stock": {
        "es": "culata ajustable", "de": "verstellbarer Schaft", "fr": "crosse réglable",
        "it": "calcio regolabile", "pt": "coronha ajustável", "ru": "регулируемый приклад",
        "pl": "kolba regulowana", "uk": "регульований приклад", "ro": "pat reglabil",
        "nl": "verstelbare kolf", "hr": "podesivi kundak", "tr": "ayarlanabilir dipçik",
        "hu": "állítható tus", "el": "ρυθμιζόμενο κοντάκι", "cs": "nastavitelná pažba",
        "sv": "justerbar kolv", "ca": "culata ajustable", "bg": "регулируем приклад",
        "da": "justerbar kolbe",
        "zh": "可调枪托", "ja": "アジャスタブルストック",
    },
    "buffer tube": {
        "es": "tubo de culata", "de": "Pufferrohr", "fr": "tube de crosse",
        "it": "tubo di calcio", "pt": "tubo de coronha", "ru": "буферная трубка",
        "pl": "rura kolby", "uk": "буферна трубка", "ro": "tub buffer",
        "nl": "bufferbuis", "hr": "tampon cijev", "tr": "tampon tüpü",
        "hu": "puffercső", "el": "σωλήνας buffer", "cs": "buffer tube",
        "sv": "buffertrör", "ca": "tub de culata", "bg": "буферна тръба",
        "da": "bufferrør",
        "zh": "缓冲管", "ja": "バッファーチューブ",
    },
    "handguard": {
        "es": "guardamanos", "de": "Handschutz", "fr": "garde-main",
        "it": "paramano", "pt": "guarda-mão", "ru": "цевьё",
        "pl": "łoże", "uk": "цівка", "ro": "apărătoare de mână",
        "nl": "handgreepbeschermer", "hr": "rukobran", "tr": "el koruyucu",
        "hu": "kézvédő", "el": "χειροφυλακτήρας", "cs": "předpažbí",
        "sv": "handskydd", "ca": "guardamans", "bg": "ръкохватка",
        "da": "håndbeskytter",
        "zh": "护木", "ja": "ハンドガード",
    },
    "rail": {
        "es": "riel", "de": "Schiene", "fr": "rail", "it": "slitta",
        "pt": "trilho", "ru": "планка", "pl": "szyna", "uk": "планка",
        "ro": "șină", "nl": "rail", "hr": "šina", "tr": "ray",
        "hu": "sín", "el": "ράγα", "cs": "lišta", "sv": "räls",
        "ca": "rail", "bg": "релса", "da": "skinne",
        "zh": "导轨", "ja": "レール",
    },
    "rail system": {
        "es": "sistema de rieles", "de": "Schienensystem", "fr": "système de rails",
        "it": "sistema di slitte", "pt": "sistema de trilhos", "ru": "система планок",
        "pl": "system szyn", "uk": "система планок", "ro": "sistem de șine",
        "nl": "railsysteem", "hr": "sustav šina", "tr": "ray sistemi",
        "hu": "sínrendszer", "el": "σύστημα ράγας", "cs": "systém lišt",
        "sv": "rälssystem", "ca": "sistema de rails", "bg": "система от релси",
        "da": "skinnesystem",
        "zh": "导轨系统", "ja": "レールシステム",
    },
    "picatinny rail": {
        "es": "riel Picatinny", "de": "Picatinny-Schiene", "fr": "rail Picatinny",
        "it": "slitta Picatinny", "pt": "trilho Picatinny", "ru": "планка Пикатинни",
        "pl": "szyna Picatinny", "uk": "планка Пікатінні", "ro": "șină Picatinny",
        "nl": "Picatinny rail", "hr": "Picatinny šina", "tr": "Picatinny rayı",
        "hu": "Picatinny sín", "el": "ράγα Picatinny", "cs": "Picatinny lišta",
        "sv": "Picatinny-räls", "ca": "rail Picatinny", "bg": "Picatinny релса",
        "da": "Picatinny-skinne",
        "zh": "皮卡汀尼导轨", "ja": "ピカティニーレール",
    },
    "upper receiver": {
        "es": "cuerpo superior", "de": "Oberteil", "fr": "partie supérieure",
        "it": "corpo superiore", "pt": "corpo superior", "ru": "верхний ресивер",
        "pl": "górna komora zamkowa", "uk": "верхній ресівер", "ro": "receptor superior",
        "nl": "bovenlichaam", "hr": "gornji prijemnik", "tr": "üst gövde",
        "hu": "felső tok", "el": "άνω δέκτης", "cs": "horní tělo",
        "sv": "övre kropp", "ca": "cos superior", "bg": "горен корпус",
        "da": "overkrop",
        "zh": "上机匣", "ja": "アッパーレシーバー",
    },
    "lower receiver": {
        "es": "cuerpo inferior", "de": "Unterteil", "fr": "partie inférieure",
        "it": "corpo inferiore", "pt": "corpo inferior", "ru": "нижний ресивер",
        "pl": "dolna komora zamkowa", "uk": "нижній ресівер", "ro": "receptor inferior",
        "nl": "onderlichaam", "hr": "donji prijemnik", "tr": "alt gövde",
        "hu": "alsó tok", "el": "κάτω δέκτης", "cs": "dolní tělo",
        "sv": "nedre kropp", "ca": "cos inferior", "bg": "долен корпус",
        "da": "underkrop",
        "zh": "下机匣", "ja": "ロワーレシーバー",
    },
    "receiver": {
        "es": "cuerpo", "de": "Gehäuse", "fr": "corps", "it": "corpo",
        "pt": "corpo", "ru": "ресивер", "pl": "komora zamkowa", "uk": "ресівер",
        "ro": "receptor", "nl": "lichaam", "hr": "prijemnik", "tr": "gövde",
        "hu": "tok", "el": "δέκτης", "cs": "tělo", "sv": "kropp",
        "ca": "cos", "bg": "корпус", "da": "krop",
        "zh": "机匣", "ja": "レシーバー",
    },
    "bolt": {
        "es": "cerrojo", "de": "Verschluss", "fr": "culasse", "it": "otturatore",
        "pt": "ferrolho", "ru": "затвор", "pl": "zamek", "uk": "затвор",
        "ro": "închizător", "nl": "grendel", "hr": "zatvarač", "tr": "sürgü",
        "hu": "zár", "el": "κλείστρο", "cs": "závěr", "sv": "slutstycke",
        "ca": "forrellat", "bg": "затвор", "da": "bolt",
        "zh": "枪栓", "ja": "ボルト",
    },
    "charging handle": {
        "es": "manija de carga", "de": "Ladegriff", "fr": "levier d'armement",
        "it": "leva di armamento", "pt": "alavanca de carregamento",
        "ru": "рукоятка заряжания", "pl": "rączka przeładowania",
        "uk": "рукоятка заряджання", "ro": "manetă de armare",
        "nl": "laadgreep", "hr": "ručka za napinjanje", "tr": "şarj kolu",
        "hu": "felhúzókar", "el": "μοχλός οπλισμού", "cs": "natažení závěru",
        "sv": "laddhandtag", "ca": "maneta de càrrega", "bg": "ръкохватка за зареждане",
        "da": "ladegreb",
        "zh": "拉机柄", "ja": "チャージングハンドル",
    },
    "flash hider": {
        "es": "apagallamas", "de": "Mündungsfeuerdämpfer", "fr": "cache-flamme",
        "it": "rompifiamma", "pt": "quebra-chamas", "ru": "пламегаситель",
        "pl": "tłumik płomienia", "uk": "полумʼягасник", "ro": "parascântei",
        "nl": "vlamdemper", "hr": "prigušivač plamena", "tr": "alev gizleyici",
        "hu": "lángrejtő", "el": "κρύπτης φλόγας", "cs": "tlumič plamene",
        "sv": "flamdämpare", "ca": "paraflames", "bg": "пламегасител",
        "da": "flammeskjuler",
        "zh": "消焰器", "ja": "フラッシュハイダー",
    },
    "muzzle brake": {
        "es": "freno de boca", "de": "Mündungsbremse", "fr": "frein de bouche",
        "it": "freno di bocca", "pt": "freio de boca", "ru": "дульный тормоз",
        "pl": "hamulec wylotowy", "uk": "дульне гальмо", "ro": "frână de gură",
        "nl": "mondingsrem", "hr": "kočnica usta", "tr": "namlu freni",
        "hu": "csőszájfék", "el": "φρένο στομίου", "cs": "úsťová brzda",
        "sv": "mynningsbroms", "ca": "fre de boca", "bg": "дулен спирач",
        "da": "mundingsbremse",
        "zh": "枪口制退器", "ja": "マズルブレーキ",
    },
    "suppressor": {
        "es": "silenciador", "de": "Schalldämpfer", "fr": "silencieux",
        "it": "silenziatore", "pt": "silenciador", "ru": "глушитель",
        "pl": "tłumik", "uk": "глушник", "ro": "amortizor de sunet",
        "nl": "demper", "hr": "prigušivač", "tr": "susturucu",
        "hu": "hangtompító", "el": "σιγαστήρας", "cs": "tlumič",
        "sv": "ljuddämpare", "ca": "silenciador", "bg": "заглушител",
        "da": "lyddæmper",
        "zh": "消音器", "ja": "サプレッサー",
    },
    "silencer": {
        "es": "silenciador", "de": "Schalldämpfer", "fr": "silencieux",
        "it": "silenziatore", "pt": "silenciador", "ru": "глушитель",
        "pl": "tłumik", "uk": "глушник", "ro": "amortizor de sunet",
        "nl": "demper", "hr": "prigušivač", "tr": "susturucu",
        "hu": "hangtompító", "el": "σιγαστήρας", "cs": "tlumič",
        "sv": "ljuddämpare", "ca": "silenciador", "bg": "заглушител",
        "da": "lyddæmper",
        "zh": "消音器", "ja": "サイレンサー",
    },
    "tracer unit": {
        "es": "unidad trazadora", "de": "Tracer-Einheit", "fr": "unité tracer",
        "it": "unità tracer", "pt": "unidade tracer", "ru": "трассерная насадка",
        "pl": "nakładka tracer", "uk": "трасерна насадка", "ro": "unitate tracer",
        "nl": "tracer unit", "hr": "tracer jedinica", "tr": "tracer ünitesi",
        "hu": "tracer egység", "el": "μονάδα tracer", "cs": "tracer jednotka",
        "sv": "tracerenhet", "ca": "unitat tracer", "bg": "трасиращо устройство",
        "da": "tracerenhed",
        "zh": "曳光器", "ja": "トレーサーユニット",
    },
    "grip": {
        "es": "empuñadura", "de": "Griff", "fr": "poignée", "it": "impugnatura",
        "pt": "empunhadura", "ru": "рукоятка", "pl": "chwyt", "uk": "рукоятка",
        "ro": "mâner", "nl": "greep", "hr": "rukohvat", "tr": "kabza",
        "hu": "markolat", "el": "λαβή", "cs": "rukojeť", "sv": "grepp",
        "ca": "empunyadura", "bg": "ръкохватка", "da": "greb",
        "zh": "握把", "ja": "グリップ",
    },
    "pistol grip": {
        "es": "empuñadura de pistola", "de": "Pistolengriff", "fr": "poignée pistolet",
        "it": "impugnatura a pistola", "pt": "empunhadura tipo pistola",
        "ru": "пистолетная рукоятка", "pl": "chwyt pistoletowy",
        "uk": "пістолетна рукоятка", "ro": "mâner de pistol",
        "nl": "pistoolgreep", "hr": "pištoljski rukohvat", "tr": "tabanca kabzası",
        "hu": "pisztolymarkolat", "el": "λαβή πιστολιού", "cs": "pistolová rukojeť",
        "sv": "pistolgrepp", "ca": "empunyadura de pistola", "bg": "пистолетна ръкохватка",
        "da": "pistolgreb",
        "zh": "手枪握把", "ja": "ピストルグリップ",
    },
    "foregrip": {
        "es": "empuñadura delantera", "de": "Vordergriff", "fr": "poignée avant",
        "it": "impugnatura anteriore", "pt": "empunhadura dianteira",
        "ru": "передняя рукоятка", "pl": "chwyt przedni",
        "uk": "передня рукоятка", "ro": "mâner frontal",
        "nl": "voorgreep", "hr": "prednji rukohvat", "tr": "ön kabza",
        "hu": "előmarkolat", "el": "εμπρόσθια λαβή", "cs": "přední rukojeť",
        "sv": "framgrepp", "ca": "empunyadura davantera", "bg": "предна ръкохватка",
        "da": "frontgreb",
        "zh": "前握把", "ja": "フォアグリップ",
    },
    "magazine": {
        "es": "cargador", "de": "Magazin", "fr": "chargeur", "it": "caricatore",
        "pt": "carregador", "ru": "магазин", "pl": "magazynek", "uk": "магазин",
        "ro": "încărcător", "nl": "magazijn", "hr": "spremnik", "tr": "şarjör",
        "hu": "tár", "el": "γεμιστήρας", "cs": "zásobník", "sv": "magasin",
        "ca": "carregador", "bg": "пълнител", "da": "magasin",
        "zh": "弹匣", "ja": "マガジン",
    },
    "mag": {
        "es": "cargador", "de": "Magazin", "fr": "chargeur", "it": "caricatore",
        "pt": "carregador", "ru": "магазин", "pl": "magazynek", "uk": "магазин",
        "ro": "încărcător", "nl": "magazijn", "hr": "spremnik", "tr": "şarjör",
        "hu": "tár", "el": "γεμιστήρας", "cs": "zásobník", "sv": "magasin",
        "ca": "carregador", "bg": "пълнител", "da": "magasin",
        "zh": "弹匣", "ja": "マグ",
    },
    "mid-cap magazine": {
        "es": "cargador mid-cap", "de": "Mid-Cap Magazin", "fr": "chargeur mid-cap",
        "it": "caricatore mid-cap", "pt": "carregador mid-cap", "ru": "магазин mid-cap",
        "pl": "magazynek mid-cap", "uk": "магазин mid-cap", "ro": "încărcător mid-cap",
        "nl": "mid-cap magazijn", "hr": "mid-cap spremnik", "tr": "mid-cap şarjör",
        "hu": "mid-cap tár", "el": "γεμιστήρας mid-cap", "cs": "mid-cap zásobník",
        "sv": "mid-cap magasin", "ca": "carregador mid-cap", "bg": "mid-cap пълнител",
        "da": "mid-cap magasin",
        "zh": "中容量弹匣", "ja": "ミッドキャップマガジン",
    },
    "hi-cap magazine": {
        "es": "cargador hi-cap", "de": "Hi-Cap Magazin", "fr": "chargeur hi-cap",
        "it": "caricatore hi-cap", "pt": "carregador hi-cap", "ru": "магазин hi-cap",
        "pl": "magazynek hi-cap", "uk": "магазин hi-cap", "ro": "încărcător hi-cap",
        "nl": "hi-cap magazijn", "hr": "hi-cap spremnik", "tr": "hi-cap şarjör",
        "hu": "hi-cap tár", "el": "γεμιστήρας hi-cap", "cs": "hi-cap zásobník",
        "sv": "hi-cap magasin", "ca": "carregador hi-cap", "bg": "hi-cap пълнител",
        "da": "hi-cap magasin",
        "zh": "大容量弹匣", "ja": "多弾マガジン",
    },
    "drum magazine": {
        "es": "cargador de tambor", "de": "Trommelmagazin", "fr": "chargeur tambour",
        "it": "caricatore a tamburo", "pt": "carregador tambor", "ru": "барабанный магазин",
        "pl": "magazynek bębnowy", "uk": "барабанний магазин", "ro": "încărcător tambur",
        "nl": "trommelmagazijn", "hr": "bubanj spremnik", "tr": "tambur şarjör",
        "hu": "dobtár", "el": "τυμπανοειδής γεμιστήρας", "cs": "bubnový zásobník",
        "sv": "trummagasin", "ca": "carregador de tambor", "bg": "барабанен пълнител",
        "da": "tromlemagasin",
        "zh": "弹鼓", "ja": "ドラムマガジン",
    },
    "mag release": {
        "es": "liberador de cargador", "de": "Magazinauslöser", "fr": "largueur de chargeur",
        "it": "sgancio caricatore", "pt": "liberador de carregador",
        "ru": "кнопка сброса магазина", "pl": "zwalniacz magazynka",
        "uk": "кнопка скидання магазину", "ro": "eliberare încărcător",
        "nl": "magazijnontgrendeling", "hr": "otpuštanje spremnika", "tr": "şarjör düğmesi",
        "hu": "tárkireteszelő", "el": "απελευθέρωση γεμιστήρα", "cs": "pojistka zásobníku",
        "sv": "magasinfrigöring", "ca": "alliberador de carregador", "bg": "бутон за освобождаване на пълнителя",
        "da": "magasinudløser",
        "zh": "弹匣释放钮", "ja": "マグリリース",
    },
    "speed loader": {
        "es": "cargador rápido", "de": "Speedloader", "fr": "speed loader",
        "it": "speed loader", "pt": "speed loader", "ru": "спидлоадер",
        "pl": "speed loader", "uk": "спідлоадер", "ro": "speed loader",
        "nl": "speed loader", "hr": "speed loader", "tr": "hızlı doldurucu",
        "hu": "speed loader", "el": "speed loader", "cs": "speed loader",
        "sv": "speed loader", "ca": "carregador ràpid", "bg": "спийдлоудър",
        "da": "speed loader",
        "zh": "快速装弹器", "ja": "スピードローダー",
    },
    "bolt": {
        "es": "cerrojo", "de": "Verschluss", "fr": "culasse", "it": "otturatore",
        "pt": "ferrolho", "ru": "затвор", "pl": "zamek", "uk": "затвор",
        "ro": "închizător", "nl": "grendel", "hr": "zatvarač", "tr": "sürgü",
        "hu": "zár", "el": "κλείστρο", "cs": "závěr", "sv": "slutstycke",
        "ca": "forrellat", "bg": "затвор", "da": "bundstykke",
        "zh": "枪栓", "ja": "ボルト",
    },
    "buffer": {
        "es": "buffer", "de": "Puffer", "fr": "tampon", "it": "buffer",
        "pt": "buffer", "ru": "буфер", "pl": "bufor", "uk": "буфер",
        "ro": "buffer", "nl": "buffer", "hr": "odbojnik", "tr": "tampon",
        "hu": "ütköző", "el": "ρυθμιστής", "cs": "buffer", "sv": "buffert",
        "ca": "buffer", "bg": "буфер", "da": "buffer",
        "zh": "缓冲器", "ja": "バッファー",
    },
    "sling": {
        "es": "correa", "de": "Tragegurt", "fr": "bretelle", "it": "cinghia",
        "pt": "bandoleira", "ru": "ремень", "pl": "zawieszenie", "uk": "ремінь",
        "ro": "curea", "nl": "draagriem", "hr": "remen", "tr": "askı kayışı",
        "hu": "hordszíj", "el": "αορτήρας", "cs": "popruh", "sv": "vapenrem",
        "ca": "corretja", "bg": "каишка", "da": "bærerem",
        "zh": "枪带", "ja": "スリング",
    },
    "bipod": {
        "es": "bípode", "de": "Zweibein", "fr": "bipied", "it": "bipiede",
        "pt": "bipé", "ru": "сошки", "pl": "dwójnóg", "uk": "сошки",
        "ro": "bipod", "nl": "bipod", "hr": "dvonožac", "tr": "bipod",
        "hu": "kétlábú", "el": "δίποδο", "cs": "dvojnožka", "sv": "tvåfot",
        "ca": "bípode", "bg": "двуножник", "da": "bipod",
        "zh": "两脚架", "ja": "バイポッド",
    },

    # ══════════════════════════════════════════════════════════════
    # WEAPON TYPES
    # ══════════════════════════════════════════════════════════════

    "airsoft gun": {
        "es": "réplica de airsoft", "de": "Airsoft-Waffe", "fr": "réplique airsoft",
        "it": "replica airsoft", "pt": "réplica de airsoft", "ru": "страйкбольное оружие",
        "pl": "replika ASG", "uk": "страйкбольна зброя", "ro": "replică airsoft",
        "nl": "airsoft replica", "hr": "airsoft replika", "tr": "airsoft silahı",
        "hu": "airsoft fegyver", "el": "airsoft όπλο", "cs": "airsoftová zbraň",
        "sv": "airsoftvapen", "ca": "rèplica d'airsoft", "bg": "еърсофт оръжие",
        "da": "airsoft våben",
        "zh": "气枪", "ja": "エアソフトガン",
    },
    "airsoft rifle": {
        "es": "réplica de airsoft tipo rifle", "de": "Airsoft-Gewehr", "fr": "fusil airsoft",
        "it": "fucile airsoft", "pt": "rifle de airsoft", "ru": "страйкбольная винтовка",
        "pl": "karabin ASG", "uk": "страйкбольна гвинтівка", "ro": "pușcă airsoft",
        "nl": "airsoft geweer", "hr": "airsoft puška", "tr": "airsoft tüfek",
        "hu": "airsoft puska", "el": "airsoft τυφέκιο", "cs": "airsoftová puška",
        "sv": "airsoftgevär", "ca": "fusell d'airsoft", "bg": "еърсофт пушка",
        "da": "airsoft riffel",
        "zh": "气动步枪", "ja": "エアソフトライフル",
    },
    "airsoft pistol": {
        "es": "pistola de airsoft", "de": "Airsoft-Pistole", "fr": "pistolet airsoft",
        "it": "pistola airsoft", "pt": "pistola de airsoft", "ru": "страйкбольный пистолет",
        "pl": "pistolet ASG", "uk": "страйкбольний пістолет", "ro": "pistol airsoft",
        "nl": "airsoft pistool", "hr": "airsoft pištolj", "tr": "airsoft tabanca",
        "hu": "airsoft pisztoly", "el": "airsoft πιστόλι", "cs": "airsoftová pistole",
        "sv": "airsoftpistol", "ca": "pistola d'airsoft", "bg": "еърсофт пистолет",
        "da": "airsoft pistol",
        "zh": "气动手枪", "ja": "エアソフトピストル",
    },
    "replica": {
        "es": "réplica", "de": "Replik", "fr": "réplique", "it": "replica",
        "pt": "réplica", "ru": "реплика", "pl": "replika", "uk": "репліка",
        "ro": "replică", "nl": "replica", "hr": "replika", "tr": "replika",
        "hu": "replika", "el": "ρέπλικα", "cs": "replika", "sv": "replika",
        "ca": "rèplica", "bg": "реплика", "da": "replika",
        "zh": "复刻枪", "ja": "レプリカ",
    },
    "AEG": {
        "es": "AEG (fusil eléctrico automático)", "de": "AEG (Automatik-Elektro-Gewehr)",
        "fr": "AEG (fusil électrique automatique)", "it": "AEG (fucile elettrico automatico)",
        "pt": "AEG (arma elétrica automática)", "ru": "AEG (автоматический электропневматический привод)",
        "pl": "AEG (automatyczny karabin elektryczny)", "uk": "AEG (автоматичний електропневматичний привід)",
        "ro": "AEG (armă electrică automată)", "nl": "AEG (automatisch elektrisch geweer)",
        "hr": "AEG (automatska električna puška)", "tr": "AEG (otomatik elektrikli tüfek)",
        "hu": "AEG (automata elektromos fegyver)", "el": "AEG (αυτόματο ηλεκτρικό όπλο)",
        "cs": "AEG (automatická elektrická zbraň)", "sv": "AEG (automatiskt elgevär)",
        "ca": "AEG (fusell elèctric automàtic)", "bg": "AEG (автоматичен електрически привод)",
        "da": "AEG (automatisk elektrisk gevær)",
        "zh": "电动枪", "ja": "電動ガン",
    },
    "GBB": {
        "es": "GBB (gas blowback)", "de": "GBB (Gas Blowback)", "fr": "GBB (gas blowback)",
        "it": "GBB (gas blowback)", "pt": "GBB (gas blowback)", "ru": "GBB (газовый блоубэк)",
        "pl": "GBB (gas blowback)", "uk": "GBB (газовий блоубек)", "ro": "GBB (gas blowback)",
        "nl": "GBB (gas blowback)", "hr": "GBB (gas blowback)", "tr": "GBB (gaz geri tepmeli)",
        "hu": "GBB (gas blowback)", "el": "GBB (gas blowback)", "cs": "GBB (gas blowback)",
        "sv": "GBB (gas blowback)", "ca": "GBB (gas blowback)", "bg": "GBB (газов блоубек)",
        "da": "GBB (gas blowback)",
        "zh": "气吹回膛", "ja": "ガスブローバック",
    },
    "gas blowback": {
        "es": "gas blowback", "de": "Gas Blowback", "fr": "gas blowback",
        "it": "gas blowback", "pt": "gas blowback", "ru": "газовый блоубэк",
        "pl": "gas blowback", "uk": "газовий блоубек", "ro": "gas blowback",
        "nl": "gas blowback", "hr": "gas blowback", "tr": "gaz geri tepmeli",
        "hu": "gas blowback", "el": "gas blowback", "cs": "gas blowback",
        "sv": "gas blowback", "ca": "gas blowback", "bg": "газов блоубек",
        "da": "gas blowback",
        "zh": "气动回膛", "ja": "ガスブローバック",
    },
    "bolt action": {
        "es": "cerrojo", "de": "Repetiergewehr", "fr": "à verrou",
        "it": "a otturatore girevole-scorrevole", "pt": "ferrolho",
        "ru": "болтовой затвор", "pl": "zamek ślizgowo-obrotowy",
        "uk": "болтовий затвор", "ro": "închizător manual",
        "nl": "grendel", "hr": "repetirka", "tr": "sürgülü mekanizma",
        "hu": "tolózáras", "el": "μοχλοκίνητο", "cs": "opakovací závěr",
        "sv": "cylindermekanism", "ca": "forrellat", "bg": "болтово действие",
        "da": "boltmekanisme",
        "zh": "栓动式", "ja": "ボルトアクション",
    },
    "sniper rifle": {
        "es": "rifle de francotirador", "de": "Scharfschützengewehr", "fr": "fusil de précision",
        "it": "fucile da cecchino", "pt": "rifle sniper", "ru": "снайперская винтовка",
        "pl": "karabin snajperski", "uk": "снайперська гвинтівка", "ro": "pușcă de lunetist",
        "nl": "sluipschuttersgeweer", "hr": "snajperska puška", "tr": "keskin nişancı tüfeği",
        "hu": "mesterlövész puska", "el": "τυφέκιο ελεύθερου σκοπευτή", "cs": "odstřelovací puška",
        "sv": "prickskyttegevär", "ca": "fusell de franctirador", "bg": "снайперска пушка",
        "da": "sniperriffel",
        "zh": "狙击步枪", "ja": "スナイパーライフル",
    },
    "submachine gun": {
        "es": "subfusil", "de": "Maschinenpistole", "fr": "pistolet-mitrailleur",
        "it": "mitra", "pt": "submetralhadora", "ru": "пистолет-пулемёт",
        "pl": "pistolet maszynowy", "uk": "пістолет-кулемет", "ro": "pistol-mitralieră",
        "nl": "machinepistool", "hr": "automat", "tr": "hafif makineli tüfek",
        "hu": "géppisztoly", "el": "υποπολυβόλο", "cs": "samopal",
        "sv": "kulsprutepistol", "ca": "subfusell", "bg": "пистолет-картечница",
        "da": "maskinpistol",
        "zh": "冲锋枪", "ja": "サブマシンガン",
    },
    "shotgun": {
        "es": "escopeta", "de": "Schrotflinte", "fr": "fusil à pompe",
        "it": "fucile a pompa", "pt": "espingarda", "ru": "дробовик",
        "pl": "strzelba", "uk": "дробовик", "ro": "pușcă cu alice",
        "nl": "shotgun", "hr": "sačmarica", "tr": "pompalı tüfek",
        "hu": "sörétes puska", "el": "κυνηγετικό όπλο", "cs": "brokovnice",
        "sv": "hagelgevär", "ca": "escopeta", "bg": "пушка-помпа",
        "da": "haglgevær",
        "zh": "霰弹枪", "ja": "ショットガン",
    },
    "grenade launcher": {
        "es": "lanzagranadas", "de": "Granatwerfer", "fr": "lance-grenades",
        "it": "lanciagranate", "pt": "lança-granadas", "ru": "гранатомёт",
        "pl": "granatnik", "uk": "гранатомет", "ro": "lansator de grenade",
        "nl": "granaatwerper", "hr": "bacač granata", "tr": "bomba atar",
        "hu": "gránátvető", "el": "εκτοξευτής χειροβομβίδων", "cs": "granátomet",
        "sv": "granatkastare", "ca": "llançagranades", "bg": "гранатомет",
        "da": "granatkaster",
        "zh": "榴弹发射器", "ja": "グレネードランチャー",
    },
    "carbine": {
        "es": "carabina", "de": "Karabiner", "fr": "carabine", "it": "carabina",
        "pt": "carabina", "ru": "карабин", "pl": "karabinek", "uk": "карабін",
        "ro": "carabină", "nl": "karabijn", "hr": "karabinka", "tr": "karabina",
        "hu": "karabély", "el": "καραμπίνα", "cs": "karabina", "sv": "karbin",
        "ca": "carabina", "bg": "карабина", "da": "karabin",
        "zh": "卡宾枪", "ja": "カービン",
    },
    "assault rifle": {
        "es": "rifle de asalto", "de": "Sturmgewehr", "fr": "fusil d'assaut",
        "it": "fucile d'assalto", "pt": "fuzil de assalto", "ru": "штурмовая винтовка",
        "pl": "karabin szturmowy", "uk": "штурмова гвинтівка", "ro": "pușcă de asalt",
        "nl": "aanvalsgeweer", "hr": "jurišna puška", "tr": "taarruz tüfeği",
        "hu": "gépkarabély", "el": "τυφέκιο εφόδου", "cs": "útočná puška",
        "sv": "automatkarbiner", "ca": "fusell d'assalt", "bg": "щурмова пушка",
        "da": "stormgevær",
        "zh": "突击步枪", "ja": "アサルトライフル",
    },
    "non-blowback": {
        "es": "non-blowback (NBB)", "de": "Non-Blowback (NBB)",
        "fr": "non-blowback (NBB)", "it": "non-blowback (NBB)",
        "pt": "non-blowback (NBB)", "ru": "без блоубэка (NBB)",
        "pl": "non-blowback (NBB)", "uk": "без блоубеку (NBB)",
        "ro": "non-blowback (NBB)", "nl": "non-blowback (NBB)",
        "hr": "non-blowback (NBB)", "tr": "geri tepmesiz (NBB)",
        "hu": "non-blowback (NBB)", "el": "non-blowback (NBB)",
        "cs": "non-blowback (NBB)", "sv": "non-blowback (NBB)",
        "ca": "non-blowback (NBB)", "bg": "без блоубек (NBB)",
        "da": "non-blowback (NBB)",
        "zh": "非回膛", "ja": "ノンブローバック",
    },

    # ══════════════════════════════════════════════════════════════
    # PROPULSION / POWER
    # ══════════════════════════════════════════════════════════════

    "blowback": {
        "es": "blowback", "de": "Blowback", "fr": "blowback", "it": "blowback",
        "pt": "blowback", "ru": "блоубэк", "pl": "blowback", "uk": "блоубек",
        "ro": "blowback", "nl": "blowback", "hr": "blowback", "tr": "geri tepme",
        "hu": "blowback", "el": "blowback", "cs": "blowback", "sv": "blowback",
        "ca": "blowback", "bg": "блоубек", "da": "blowback",
        "zh": "回膛", "ja": "ブローバック",
    },
    "recoil": {
        "es": "retroceso", "de": "Rückstoß", "fr": "recul", "it": "rinculo",
        "pt": "recuo", "ru": "отдача", "pl": "odrzut", "uk": "віддача",
        "ro": "recul", "nl": "terugslag", "hr": "trzaj", "tr": "geri tepme",
        "hu": "hátralökés", "el": "ανάκρουση", "cs": "zpětný ráz", "sv": "rekyl",
        "ca": "retrocés", "bg": "откат", "da": "rekyl",
        "zh": "后坐力", "ja": "リコイル",
    },
    "green gas": {
        "es": "green gas", "de": "Green Gas", "fr": "green gas", "it": "green gas",
        "pt": "green gas", "ru": "грин газ", "pl": "green gas", "uk": "грін газ",
        "ro": "green gas", "nl": "green gas", "hr": "green gas", "tr": "green gas",
        "hu": "green gas", "el": "green gas", "cs": "green gas", "sv": "green gas",
        "ca": "green gas", "bg": "грийн газ", "da": "green gas",
        "zh": "绿气", "ja": "グリーンガス",
    },
    "battery": {
        "es": "batería", "de": "Akku", "fr": "batterie", "it": "batteria",
        "pt": "bateria", "ru": "аккумулятор", "pl": "akumulator", "uk": "акумулятор",
        "ro": "baterie", "nl": "accu", "hr": "baterija", "tr": "batarya",
        "hu": "akkumulátor", "el": "μπαταρία", "cs": "baterie", "sv": "batteri",
        "ca": "bateria", "bg": "батерия", "da": "batteri",
        "zh": "电池", "ja": "バッテリー",
    },
    "charger": {
        "es": "cargador de batería", "de": "Ladegerät", "fr": "chargeur de batterie",
        "it": "caricabatterie", "pt": "carregador de bateria", "ru": "зарядное устройство",
        "pl": "ładowarka", "uk": "зарядний пристрій", "ro": "încărcător de baterie",
        "nl": "lader", "hr": "punjač", "tr": "şarj cihazı",
        "hu": "töltő", "el": "φορτιστής", "cs": "nabíječka", "sv": "laddare",
        "ca": "carregador de bateria", "bg": "зарядно устройство", "da": "oplader",
        "zh": "充电器", "ja": "チャージャー",
    },
    "MOSFET": {
        "es": "MOSFET", "de": "MOSFET", "fr": "MOSFET", "it": "MOSFET",
        "pt": "MOSFET", "ru": "MOSFET", "pl": "MOSFET", "uk": "MOSFET",
        "ro": "MOSFET", "nl": "MOSFET", "hr": "MOSFET", "tr": "MOSFET",
        "hu": "MOSFET", "el": "MOSFET", "cs": "MOSFET", "sv": "MOSFET",
        "ca": "MOSFET", "bg": "MOSFET", "da": "MOSFET",
        "zh": "MOSFET", "ja": "MOSFET",
    },
    "rate of fire": {
        "es": "cadencia de tiro", "de": "Feuerrate", "fr": "cadence de tir",
        "it": "cadenza di tiro", "pt": "cadência de tiro", "ru": "скорострельность",
        "pl": "szybkostrzelność", "uk": "швидкострільність", "ro": "cadența de tragere",
        "nl": "vuursnelheid", "hr": "brzina paljbe", "tr": "atış hızı",
        "hu": "tűzgyorsaság", "el": "ρυθμός βολής", "cs": "kadence palby",
        "sv": "eldhastighet", "ca": "cadència de tir", "bg": "скорост на стрелба",
        "da": "skudhastighed",
        "zh": "射速", "ja": "発射速度",
    },
    "muzzle velocity": {
        "es": "velocidad de boca", "de": "Mündungsgeschwindigkeit", "fr": "vitesse à la bouche",
        "it": "velocità alla bocca", "pt": "velocidade de saída", "ru": "дульная скорость",
        "pl": "prędkość wylotowa", "uk": "дульна швидкість", "ro": "viteza la gură",
        "nl": "mondingssnelheid", "hr": "brzina izlaza", "tr": "namlu hızı",
        "hu": "csőtorkolati sebesség", "el": "ταχύτητα στομίου", "cs": "úsťová rychlost",
        "sv": "mynningshastighet", "ca": "velocitat de boca", "bg": "дулна скорост",
        "da": "mundingshastighed",
        "zh": "枪口初速", "ja": "初速",
    },

    # ══════════════════════════════════════════════════════════════
    # AMMUNITION
    # ══════════════════════════════════════════════════════════════

    "BB": {
        "es": "BB", "de": "BB", "fr": "BB", "it": "BB", "pt": "BB",
        "ru": "шар", "pl": "kulka", "uk": "кулька", "ro": "BB",
        "nl": "BB", "hr": "kuglica", "tr": "BB", "hu": "BB",
        "el": "BB", "cs": "BB", "sv": "BB", "ca": "BB", "bg": "BB", "da": "BB",
        "zh": "BB弹", "ja": "BB弾",
    },
    "BBs": {
        "es": "BBs", "de": "BBs", "fr": "BBs", "it": "BBs", "pt": "BBs",
        "ru": "шары", "pl": "kulki", "uk": "кульки", "ro": "BBs",
        "nl": "BBs", "hr": "kuglice", "tr": "BBler", "hu": "BBk",
        "el": "BBs", "cs": "BBčka", "sv": "BBs", "ca": "BBs", "bg": "BBта", "da": "BBs",
        "zh": "BB弹", "ja": "BB弾",
    },
    "biodegradable BBs": {
        "es": "BBs biodegradables", "de": "biologisch abbaubare BBs",
        "fr": "BBs biodégradables", "it": "BBs biodegradabili",
        "pt": "BBs biodegradáveis", "ru": "биоразлагаемые шары",
        "pl": "kulki biodegradowalne", "uk": "біорозкладні кульки",
        "ro": "BBs biodegradabile", "nl": "biologisch afbreekbare BBs",
        "hr": "biorazgradive kuglice", "tr": "biyobozunur BBler",
        "hu": "biológiailag lebomló BBk", "el": "βιοαποδομήσιμα BBs",
        "cs": "biologicky rozložitelná BBčka", "sv": "bionedbrytbara BBs",
        "ca": "BBs biodegradables", "bg": "биоразградими BBта",
        "da": "bionedbrydelige BBs",
        "zh": "可降解BB弹", "ja": "バイオBB弾",
    },
    "tracer BBs": {
        "es": "BBs trazadoras", "de": "Tracer BBs", "fr": "BBs traçantes",
        "it": "BBs traccianti", "pt": "BBs traçantes", "ru": "трассирующие шары",
        "pl": "kulki smugowe", "uk": "трасуючі кульки", "ro": "BBs trasoare",
        "nl": "tracer BBs", "hr": "tracer kuglice", "tr": "izleyici BBler",
        "hu": "fényjeles BBk", "el": "ιχνηθετικά BBs", "cs": "tracer BBčka",
        "sv": "tracer BBs", "ca": "BBs traçadores", "bg": "трасиращи BBта",
        "da": "tracer BBs",
        "zh": "曳光BB弹", "ja": "トレーサーBB弾",
    },
    "grenade": {
        "es": "granada", "de": "Granate", "fr": "grenade", "it": "granata",
        "pt": "granada", "ru": "граната", "pl": "granat", "uk": "граната",
        "ro": "grenadă", "nl": "granaat", "hr": "granata", "tr": "el bombası",
        "hu": "gránát", "el": "χειροβομβίδα", "cs": "granát", "sv": "granat",
        "ca": "granada", "bg": "граната", "da": "granat",
        "zh": "手榴弹", "ja": "グレネード",
    },
    "lubricant": {
        "es": "lubricante", "de": "Schmiermittel", "fr": "lubrifiant", "it": "lubrificante",
        "pt": "lubrificante", "ru": "смазка", "pl": "smar", "uk": "мастило",
        "ro": "lubrifiant", "nl": "smeermiddel", "hr": "mazivo", "tr": "yağlayıcı",
        "hu": "kenőanyag", "el": "λιπαντικό", "cs": "mazivo", "sv": "smörjmedel",
        "ca": "lubricant", "bg": "смазка", "da": "smøremiddel",
        "zh": "润滑剂", "ja": "ルブリカント",
    },
    "silicone oil": {
        "es": "aceite de silicona", "de": "Silikonöl", "fr": "huile de silicone",
        "it": "olio siliconico", "pt": "óleo de silicone", "ru": "силиконовое масло",
        "pl": "olej silikonowy", "uk": "силіконове масло", "ro": "ulei de silicon",
        "nl": "siliconolie", "hr": "silikonsko ulje", "tr": "silikon yağı",
        "hu": "szilikonolaj", "el": "σιλικονέλαιο", "cs": "silikonový olej",
        "sv": "silikonolja", "ca": "oli de silicona", "bg": "силиконово масло",
        "da": "silikoneolie",
        "zh": "硅油", "ja": "シリコンオイル",
    },
    "spray paint": {
        "es": "pintura en spray", "de": "Sprühfarbe", "fr": "peinture en spray",
        "it": "vernice spray", "pt": "tinta spray", "ru": "аэрозольная краска",
        "pl": "farba w sprayu", "uk": "аерозольна фарба", "ro": "vopsea spray",
        "nl": "spuitverf", "hr": "boja u spreju", "tr": "sprey boya",
        "hu": "festékspray", "el": "σπρέι βαφής", "cs": "barva ve spreji",
        "sv": "sprayfärg", "ca": "pintura en esprai", "bg": "спрей боя",
        "da": "spraymaling",
        "zh": "喷漆", "ja": "スプレーペイント",
    },

    # ══════════════════════════════════════════════════════════════
    # OPTICS & ACCESSORIES
    # ══════════════════════════════════════════════════════════════

    "red dot sight": {
        "es": "visor de punto rojo", "de": "Rotpunktvisier", "fr": "viseur point rouge",
        "it": "mirino punto rosso", "pt": "mira de ponto vermelho", "ru": "коллиматорный прицел",
        "pl": "celownik kolimatorowy", "uk": "коліматорний приціл", "ro": "punct roșu",
        "nl": "rood punt vizier", "hr": "crvena točka", "tr": "kırmızı nokta nişangah",
        "hu": "red dot irányzék", "el": "κόκκινη κουκκίδα", "cs": "kolimátor",
        "sv": "rödpunktssikte", "ca": "visor de punt vermell", "bg": "червена точка",
        "da": "rødpunktsigte",
        "zh": "红点瞄准镜", "ja": "ドットサイト",
    },
    "holographic sight": {
        "es": "visor holográfico", "de": "holographisches Visier", "fr": "viseur holographique",
        "it": "mirino olografico", "pt": "mira holográfica", "ru": "голографический прицел",
        "pl": "celownik holograficzny", "uk": "голографічний приціл", "ro": "vizor holographic",
        "nl": "holografisch vizier", "hr": "holografski nišan", "tr": "holografik nişangah",
        "hu": "holografikus irányzék", "el": "ολογραφικό σκοπευτικό", "cs": "holografický zaměřovač",
        "sv": "holografiskt sikte", "ca": "visor hologràfic", "bg": "холографичен прицел",
        "da": "holografisk sigte",
        "zh": "全息瞄准镜", "ja": "ホロサイト",
    },
    "scope": {
        "es": "mira telescópica", "de": "Zielfernrohr", "fr": "lunette de visée",
        "it": "cannocchiale", "pt": "luneta", "ru": "оптический прицел",
        "pl": "luneta", "uk": "оптичний приціл", "ro": "lunetă",
        "nl": "richtkijker", "hr": "optički nišan", "tr": "dürbün",
        "hu": "távcső", "el": "τηλεσκοπικό σκοπευτικό", "cs": "puškohled",
        "sv": "kikarsikte", "ca": "mira telescòpica", "bg": "оптичен прицел",
        "da": "kikkertsigte",
        "zh": "瞄准镜", "ja": "スコープ",
    },
    "iron sights": {
        "es": "miras metálicas", "de": "Kimme und Korn", "fr": "organes de visée",
        "it": "mire metalliche", "pt": "miras de ferro", "ru": "механический прицел",
        "pl": "przyrządy celownicze", "uk": "механічний приціл", "ro": "puncte de ochire",
        "nl": "ijzeren vizier", "hr": "mehanički nišan", "tr": "mekanik nişangah",
        "hu": "mechanikus irányzék", "el": "μεταλλικά σκοπευτικά", "cs": "mechanické mířidla",
        "sv": "mekaniskt sikte", "ca": "mires metàl·liques", "bg": "механичен прицел",
        "da": "mekanisk sigte",
        "zh": "机械瞄具", "ja": "アイアンサイト",
    },
    "flashlight": {
        "es": "linterna táctica", "de": "taktische Taschenlampe", "fr": "lampe tactique",
        "it": "torcia tattica", "pt": "lanterna tática", "ru": "тактический фонарь",
        "pl": "latarka taktyczna", "uk": "тактичний ліхтар", "ro": "lanternă tactică",
        "nl": "tactische zaklamp", "hr": "taktička svjetiljka", "tr": "taktik el feneri",
        "hu": "taktikai lámpa", "el": "τακτικός φακός", "cs": "taktická svítilna",
        "sv": "taktisk ficklampa", "ca": "llanterna tàctica", "bg": "тактическо фенерче",
        "da": "taktisk lommelygte",
        "zh": "手电筒", "ja": "フラッシュライト",
    },
    "magnifier": {
        "es": "magnificador", "de": "Vergrößerungsglas", "fr": "magnifier",
        "it": "moltiplicatore", "pt": "magnificador", "ru": "магнифайер",
        "pl": "powiększalnik", "uk": "магніфаєр", "ro": "magnificator",
        "nl": "vergroter", "hr": "povećalo", "tr": "büyüteç",
        "hu": "nagyító", "el": "μεγεθυντής", "cs": "zvětšovák",
        "sv": "förstorare", "ca": "magnificador", "bg": "магнифайер",
        "da": "forstørrer",
        "zh": "放大镜", "ja": "マグニファイア",
    },
    "scope mount": {
        "es": "montura de óptica", "de": "Zielfernrohrmontage", "fr": "montage de lunette",
        "it": "montaggio ottica", "pt": "montagem de luneta", "ru": "крепление прицела",
        "pl": "montaż lunety", "uk": "кріплення прицілу", "ro": "montură lunetă",
        "nl": "richtkijkermontage", "hr": "nosač optike", "tr": "dürbün montajı",
        "hu": "távcsőszerelék", "el": "βάση σκοπευτικού", "cs": "montáž puškohledu",
        "sv": "kikarsiktesmontage", "ca": "muntura d'òptica", "bg": "монтаж на прицел",
        "da": "kikkertmontering",
        "zh": "镜座", "ja": "スコープマウント",
    },
    "scope rings": {
        "es": "anillas de óptica", "de": "Zielfernrohrringe", "fr": "anneaux de lunette",
        "it": "anelli per ottica", "pt": "anéis de luneta", "ru": "кольца для прицела",
        "pl": "pierścienie lunety", "uk": "кільця для прицілу", "ro": "inele lunetă",
        "nl": "richtkijkerringen", "hr": "prstenovi optike", "tr": "dürbün halkaları",
        "hu": "távcsőgyűrűk", "el": "δαχτυλίδια σκοπευτικού", "cs": "kroužky puškohledu",
        "sv": "kikarsiktesringar", "ca": "anelles d'òptica", "bg": "пръстени за прицел",
        "da": "kikkertringe",
        "zh": "镜环", "ja": "スコープリング",
    },
    "laser sight": {
        "es": "láser táctico", "de": "Laservisier", "fr": "viseur laser",
        "it": "puntatore laser", "pt": "mira laser", "ru": "лазерный прицел",
        "pl": "celownik laserowy", "uk": "лазерний приціл", "ro": "laser tactic",
        "nl": "laservizier", "hr": "laserski nišan", "tr": "lazer nişangah",
        "hu": "lézeres irányzék", "el": "σκοπευτικό λέιζερ", "cs": "laserový zaměřovač",
        "sv": "lasersikte", "ca": "visor làser", "bg": "лазерен прицел",
        "da": "lasersigte",
        "zh": "激光瞄准器", "ja": "レーザーサイト",
    },
    "PEQ box": {
        "es": "PEQ box", "de": "PEQ-Box", "fr": "boîtier PEQ",
        "it": "PEQ box", "pt": "PEQ box", "ru": "блок PEQ",
        "pl": "PEQ box", "uk": "блок PEQ", "ro": "PEQ box",
        "nl": "PEQ box", "hr": "PEQ kutija", "tr": "PEQ kutusu",
        "hu": "PEQ doboz", "el": "PEQ box", "cs": "PEQ box",
        "sv": "PEQ-box", "ca": "PEQ box", "bg": "PEQ кутия",
        "da": "PEQ-boks",
        "zh": "PEQ盒", "ja": "PEQボックス",
    },
    "pressure switch": {
        "es": "pulsador remoto", "de": "Druckschalter", "fr": "interrupteur déporté",
        "it": "pressostato remoto", "pt": "interruptor de pressão",
        "ru": "выносная кнопка", "pl": "włącznik naciskowy",
        "uk": "виносна кнопка", "ro": "întrerupător cu presiune",
        "nl": "drukschakelaar", "hr": "prekidač na pritisak", "tr": "basınç anahtarı",
        "hu": "nyomókapcsoló", "el": "διακόπτης πίεσης", "cs": "tlačítkový spínač",
        "sv": "tryckbrytare", "ca": "polsador remot", "bg": "бутон за натиск",
        "da": "trykknap",
        "zh": "压力开关", "ja": "プレッシャースイッチ",
    },
    "lens protector": {
        "es": "protector de lente", "de": "Linsenschutz", "fr": "protège-lentille",
        "it": "protezione lente", "pt": "protetor de lente", "ru": "защита линзы",
        "pl": "osłona soczewki", "uk": "захист лінзи", "ro": "protecție lentilă",
        "nl": "lensbeschermer", "hr": "zaštita leće", "tr": "lens koruyucu",
        "hu": "lencse védő", "el": "προστατευτικό φακού", "cs": "ochrana čočky",
        "sv": "linsskydd", "ca": "protector de lent", "bg": "предпазител за леща",
        "da": "linsebeskytter",
        "zh": "镜片保护器", "ja": "レンズプロテクター",
    },
    "scope riser": {
        "es": "elevador de óptica", "de": "Zielfernrohrerhöhung", "fr": "rehausse de lunette",
        "it": "rialzo per ottica", "pt": "elevador de luneta", "ru": "подъёмник прицела",
        "pl": "podwyższenie lunety", "uk": "підвищувач прицілу", "ro": "ridicător lunetă",
        "nl": "richtkijkerverhoger", "hr": "podizač optike", "tr": "dürbün yükseltici",
        "hu": "távcsőemelő", "el": "ανυψωτής σκοπευτικού", "cs": "zvýšení puškohledu",
        "sv": "kikarsiktesförhöjare", "ca": "elevador d'òptica", "bg": "повдигач за прицел",
        "da": "kikkertforhøjer",
        "zh": "镜座增高器", "ja": "スコープライザー",
    },

    # ══════════════════════════════════════════════════════════════
    # RAIL SYSTEMS
    # ══════════════════════════════════════════════════════════════

    "picatinny": {
        "es": "picatinny", "de": "Picatinny", "fr": "picatinny", "it": "picatinny",
        "pt": "picatinny", "ru": "планка Пикатинни", "pl": "picatinny",
        "uk": "планка Пікатінні", "ro": "picatinny", "nl": "picatinny",
        "hr": "picatinny", "tr": "picatinny", "hu": "picatinny",
        "el": "picatinny", "cs": "picatinny", "sv": "picatinny",
        "ca": "picatinny", "bg": "пикатини", "da": "picatinny",
        "zh": "皮卡汀尼", "ja": "ピカティニー",
    },
    "M-LOK": {
        "es": "M-LOK", "de": "M-LOK", "fr": "M-LOK", "it": "M-LOK",
        "pt": "M-LOK", "ru": "M-LOK", "pl": "M-LOK", "uk": "M-LOK",
        "ro": "M-LOK", "nl": "M-LOK", "hr": "M-LOK", "tr": "M-LOK",
        "hu": "M-LOK", "el": "M-LOK", "cs": "M-LOK", "sv": "M-LOK",
        "ca": "M-LOK", "bg": "M-LOK", "da": "M-LOK",
        "zh": "M-LOK", "ja": "M-LOK",
    },
    "keymod": {
        "es": "keymod", "de": "KeyMod", "fr": "keymod", "it": "keymod",
        "pt": "keymod", "ru": "KeyMod", "pl": "keymod", "uk": "KeyMod",
        "ro": "keymod", "nl": "keymod", "hr": "keymod", "tr": "keymod",
        "hu": "keymod", "el": "keymod", "cs": "keymod", "sv": "keymod",
        "ca": "keymod", "bg": "KeyMod", "da": "keymod",
        "zh": "KeyMod", "ja": "キーモッド",
    },
    "MOLLE": {
        "es": "MOLLE", "de": "MOLLE", "fr": "MOLLE", "it": "MOLLE",
        "pt": "MOLLE", "ru": "MOLLE", "pl": "MOLLE", "uk": "MOLLE",
        "ro": "MOLLE", "nl": "MOLLE", "hr": "MOLLE", "tr": "MOLLE",
        "hu": "MOLLE", "el": "MOLLE", "cs": "MOLLE", "sv": "MOLLE",
        "ca": "MOLLE", "bg": "MOLLE", "da": "MOLLE",
        "zh": "MOLLE", "ja": "MOLLE",
    },

    # ══════════════════════════════════════════════════════════════
    # TACTICAL GEAR
    # ══════════════════════════════════════════════════════════════

    "plate carrier": {
        "es": "portaplacas", "de": "Plattenträger", "fr": "porte-plaques",
        "it": "plate carrier", "pt": "colete porta-placas", "ru": "плитоноска",
        "pl": "kamizelka na płyty", "uk": "плитоноска", "ro": "port-plăci",
        "nl": "plaatdrager", "hr": "nosač ploča", "tr": "plaka taşıyıcı",
        "hu": "lemezviselő", "el": "φορέας πλακών", "cs": "nosič plátů",
        "sv": "platbärare", "ca": "portaplaques", "bg": "плейт кериър",
        "da": "pladebærer",
        "zh": "板甲背心", "ja": "プレートキャリア",
    },
    "tactical vest": {
        "es": "chaleco táctico", "de": "taktische Weste", "fr": "gilet tactique",
        "it": "gilet tattico", "pt": "colete tático", "ru": "тактический жилет",
        "pl": "kamizelka taktyczna", "uk": "тактичний жилет", "ro": "vestă tactică",
        "nl": "tactisch vest", "hr": "taktički prsluk", "tr": "taktik yelek",
        "hu": "taktikai mellény", "el": "τακτικό γιλέκο", "cs": "taktická vesta",
        "sv": "taktisk väst", "ca": "armilla tàctica", "bg": "тактическа жилетка",
        "da": "taktisk vest",
        "zh": "战术背心", "ja": "タクティカルベスト",
    },
    "magazine pouch": {
        "es": "portacargador", "de": "Magazintasche", "fr": "porte-chargeur",
        "it": "porta caricatore", "pt": "porta-carregador", "ru": "подсумок для магазинов",
        "pl": "ładownica", "uk": "підсумок для магазинів", "ro": "buzunar pentru încărcător",
        "nl": "magazijntas", "hr": "futrola za spremnike", "tr": "şarjör cebi",
        "hu": "tártáska", "el": "θήκη γεμιστήρα", "cs": "sumka na zásobníky",
        "sv": "magasinficka", "ca": "portacarregador", "bg": "джоб за пълнители",
        "da": "magasinlomme",
        "zh": "弹匣包", "ja": "マガジンポーチ",
    },
    "holster": {
        "es": "funda", "de": "Holster", "fr": "holster", "it": "fondina",
        "pt": "coldre", "ru": "кобура", "pl": "kabura", "uk": "кобура",
        "ro": "toc", "nl": "holster", "hr": "futrola", "tr": "kılıf",
        "hu": "pisztolytáska", "el": "θήκη πιστολιού", "cs": "pouzdro", "sv": "hölster",
        "ca": "funda", "bg": "кобур", "da": "hylster",
        "zh": "枪套", "ja": "ホルスター",
    },
    "helmet": {
        "es": "casco", "de": "Helm", "fr": "casque", "it": "elmetto",
        "pt": "capacete", "ru": "шлем", "pl": "hełm", "uk": "шолом",
        "ro": "cască", "nl": "helm", "hr": "kaciga", "tr": "kask",
        "hu": "sisak", "el": "κράνος", "cs": "helma", "sv": "hjälm",
        "ca": "casc", "bg": "шлем", "da": "hjelm",
        "zh": "头盔", "ja": "ヘルメット",
    },
    "chest rig": {
        "es": "chest rig", "de": "Chest Rig", "fr": "chest rig",
        "it": "chest rig", "pt": "chest rig", "ru": "чест риг",
        "pl": "chest rig", "uk": "чест ріг", "ro": "chest rig",
        "nl": "chest rig", "hr": "chest rig", "tr": "göğüs teçhizatı",
        "hu": "chest rig", "el": "chest rig", "cs": "chest rig",
        "sv": "chest rig", "ca": "chest rig", "bg": "чест риг",
        "da": "chest rig",
        "zh": "胸挂", "ja": "チェストリグ",
    },
    "pouch": {
        "es": "bolsillo táctico", "de": "Tasche", "fr": "pochette tactique",
        "it": "tasca tattica", "pt": "bolso tático", "ru": "подсумок",
        "pl": "ładownica", "uk": "підсумок", "ro": "buzunar tactic",
        "nl": "tactische tas", "hr": "torbica", "tr": "cep", "hu": "táska",
        "el": "τακτική θήκη", "cs": "sumka", "sv": "taktisk ficka",
        "ca": "butxaca tàctica", "bg": "тактически джоб", "da": "taktisk lomme",
        "zh": "附件包", "ja": "ポーチ",
    },
    "dump pouch": {
        "es": "bolsa de descarga", "de": "Dump Pouch", "fr": "pochette de vidage",
        "it": "dump pouch", "pt": "bolsa de descarga", "ru": "сбросной подсумок",
        "pl": "ładownica zrzutowa", "uk": "скидний підсумок", "ro": "buzunar de descărcare",
        "nl": "dump pouch", "hr": "torbica za prazne spremnike", "tr": "boşaltma cebi",
        "hu": "dump pouch", "el": "θήκη απόρριψης", "cs": "vyhazovací sumka",
        "sv": "dump pouch", "ca": "bossa de descàrrega", "bg": "контейнер за изхвърляне",
        "da": "dump pouch",
        "zh": "回收袋", "ja": "ダンプポーチ",
    },
    "tactical belt": {
        "es": "cinturón táctico", "de": "taktischer Gürtel", "fr": "ceinture tactique",
        "it": "cintura tattica", "pt": "cinto tático", "ru": "тактический пояс",
        "pl": "pas taktyczny", "uk": "тактичний пояс", "ro": "centură tactică",
        "nl": "tactische riem", "hr": "taktički pojas", "tr": "taktik kemer",
        "hu": "taktikai öv", "el": "τακτική ζώνη", "cs": "taktický opasek",
        "sv": "taktiskt bälte", "ca": "cinturó tàctic", "bg": "тактически колан",
        "da": "taktisk bælte",
        "zh": "战术腰带", "ja": "タクティカルベルト",
    },
    "gun bag": {
        "es": "bolsa para réplica", "de": "Waffentasche", "fr": "housse de transport",
        "it": "sacca per replica", "pt": "bolsa para réplica", "ru": "чехол для оружия",
        "pl": "pokrowiec na replikę", "uk": "чохол для репліки", "ro": "geantă pentru replică",
        "nl": "wapentas", "hr": "torba za repliku", "tr": "silah çantası",
        "hu": "fegyvertáska", "el": "θήκη όπλου", "cs": "obal na zbraň",
        "sv": "vapenfodral", "ca": "bossa per a rèplica", "bg": "чанта за оръжие",
        "da": "våbentaske",
        "zh": "枪包", "ja": "ガンバッグ",
    },
    "tactical pants": {
        "es": "pantalones tácticos", "de": "taktische Hose", "fr": "pantalon tactique",
        "it": "pantaloni tattici", "pt": "calças táticas", "ru": "тактические штаны",
        "pl": "spodnie taktyczne", "uk": "тактичні штани", "ro": "pantaloni tactici",
        "nl": "tactische broek", "hr": "taktičke hlače", "tr": "taktik pantolon",
        "hu": "taktikai nadrág", "el": "τακτικό παντελόνι", "cs": "taktické kalhoty",
        "sv": "taktiska byxor", "ca": "pantalons tàctics", "bg": "тактически панталони",
        "da": "taktiske bukser",
        "zh": "战术裤", "ja": "タクティカルパンツ",
    },
    "gloves": {
        "es": "guantes", "de": "Handschuhe", "fr": "gants", "it": "guanti",
        "pt": "luvas", "ru": "перчатки", "pl": "rękawice", "uk": "рукавиці",
        "ro": "mănuși", "nl": "handschoenen", "hr": "rukavice", "tr": "eldiven",
        "hu": "kesztyű", "el": "γάντια", "cs": "rukavice", "sv": "handskar",
        "ca": "guants", "bg": "ръкавици", "da": "handsker",
        "zh": "手套", "ja": "グローブ",
    },
    "knee pads": {
        "es": "rodilleras", "de": "Knieschoner", "fr": "genouillères",
        "it": "ginocchiere", "pt": "joelheiras", "ru": "наколенники",
        "pl": "nakolanniki", "uk": "наколінники", "ro": "genunchiere",
        "nl": "kniebeschermers", "hr": "štitnici za koljena", "tr": "dizlik",
        "hu": "térdvédő", "el": "επιγονατίδες", "cs": "kolenní chrániče",
        "sv": "knäskydd", "ca": "genolleres", "bg": "наколенки",
        "da": "knæbeskyttere",
        "zh": "护膝", "ja": "ニーパッド",
    },
    "hydration pack": {
        "es": "mochila de hidratación", "de": "Trinkrucksack", "fr": "sac d'hydratation",
        "it": "zaino idratazione", "pt": "mochila de hidratação",
        "ru": "гидратор", "pl": "plecak hydracyjny", "uk": "гідратор",
        "ro": "rucsac de hidratare", "nl": "drinkrugzak", "hr": "hidracijski ruksak",
        "tr": "hidrasyon çantası", "hu": "hidrációs hátizsák",
        "el": "σακίδιο ενυδάτωσης", "cs": "hydratační batoh",
        "sv": "vätskeryggsäck", "ca": "motxilla d'hidratació", "bg": "хидратираща раница",
        "da": "drikkepose",
        "zh": "水袋包", "ja": "ハイドレーションパック",
    },
    "patch": {
        "es": "parche", "de": "Patch", "fr": "écusson", "it": "toppa",
        "pt": "patch", "ru": "патч", "pl": "naszywka", "uk": "патч",
        "ro": "ecuson", "nl": "patch", "hr": "zakrpa", "tr": "yama",
        "hu": "felvarró", "el": "σήμα", "cs": "nášivka", "sv": "emblem",
        "ca": "pedaç", "bg": "нашивка", "da": "patch",
        "zh": "臂章", "ja": "パッチ",
    },

    # ══════════════════════════════════════════════════════════════
    # PROTECTION
    # ══════════════════════════════════════════════════════════════

    "goggles": {
        "es": "gafas de protección", "de": "Schutzbrille", "fr": "lunettes de protection",
        "it": "occhiali protettivi", "pt": "óculos de proteção", "ru": "защитные очки",
        "pl": "gogle ochronne", "uk": "захисні окуляри", "ro": "ochelari de protecție",
        "nl": "beschermbril", "hr": "zaštitne naočale", "tr": "koruyucu gözlük",
        "hu": "védőszemüveg", "el": "προστατευτικά γυαλιά", "cs": "ochranné brýle",
        "sv": "skyddsglasögon", "ca": "ulleres de protecció", "bg": "предпазни очила",
        "da": "beskyttelsesbriller",
        "zh": "护目镜", "ja": "ゴーグル",
    },
    "full face mask": {
        "es": "máscara facial completa", "de": "Vollgesichtsmaske", "fr": "masque intégral",
        "it": "maschera integrale", "pt": "máscara facial completa",
        "ru": "полнолицевая маска", "pl": "maska pełna",
        "uk": "повнолицева маска", "ro": "mască integrală",
        "nl": "volledig gezichtsmasker", "hr": "puna maska za lice",
        "tr": "tam yüz maskesi", "hu": "teljes arcvédő maszk",
        "el": "μάσκα πλήρους προσώπου", "cs": "celoobličejová maska",
        "sv": "heltäckande ansiktsmask", "ca": "màscara facial completa",
        "bg": "маска за цялото лице", "da": "heldækkende ansigtsmaske",
        "zh": "全脸面罩", "ja": "フルフェイスマスク",
    },
    "mesh mask": {
        "es": "máscara de malla", "de": "Gittermaske", "fr": "masque en grillage",
        "it": "maschera a rete", "pt": "máscara de malha", "ru": "сетчатая маска",
        "pl": "maska siatkowa", "uk": "сітчаста маска", "ro": "mască de plasă",
        "nl": "gaasmasker", "hr": "mrežasta maska", "tr": "ağ maske",
        "hu": "hálós maszk", "el": "μάσκα πλέγματος", "cs": "síťovaná maska",
        "sv": "nätmask", "ca": "màscara de malla", "bg": "мрежеста маска",
        "da": "netmaske",
        "zh": "铁网面罩", "ja": "メッシュマスク",
    },
    "eye protection": {
        "es": "protección ocular", "de": "Augenschutz", "fr": "protection oculaire",
        "it": "protezione oculare", "pt": "proteção ocular", "ru": "защита глаз",
        "pl": "ochrona oczu", "uk": "захист очей", "ro": "protecție oculară",
        "nl": "oogbescherming", "hr": "zaštita očiju", "tr": "göz koruması",
        "hu": "szemvédelem", "el": "προστασία ματιών", "cs": "ochrana očí",
        "sv": "ögonskydd", "ca": "protecció ocular", "bg": "защита за очите",
        "da": "øjenbeskyttelse",
        "zh": "护目", "ja": "アイプロテクション",
    },

    # ══════════════════════════════════════════════════════════════
    # GAMEPLAY
    # ══════════════════════════════════════════════════════════════

    "CQB": {
        "es": "CQB (combate en espacios cerrados)", "de": "CQB (Nahkampf)",
        "fr": "CQB (combat rapproché)", "it": "CQB (combattimento ravvicinato)",
        "pt": "CQB (combate em espaço confinado)", "ru": "CQB (ближний бой)",
        "pl": "CQB (walka w zamkniętych pomieszczeniach)", "uk": "CQB (ближній бій)",
        "ro": "CQB (luptă la distanță mică)", "nl": "CQB (korte afstand gevecht)",
        "hr": "CQB (borba u zatvorenom)", "tr": "CQB (yakın muharebe)",
        "hu": "CQB (közelharc)", "el": "CQB (μάχη σε κλειστό χώρο)",
        "cs": "CQB (boj zblízka)", "sv": "CQB (närstrid)",
        "ca": "CQB (combat en espais tancats)", "bg": "CQB (бой в сграда)",
        "da": "CQB (nærkamp)",
        "zh": "近距离作战", "ja": "CQB",
    },
    "milsim": {
        "es": "milsim (simulación militar)", "de": "MilSim (Militärsimulation)",
        "fr": "milsim (simulation militaire)", "it": "milsim (simulazione militare)",
        "pt": "milsim (simulação militar)", "ru": "милсим (военная симуляция)",
        "pl": "milsim (symulacja wojskowa)", "uk": "мілсім (військова симуляція)",
        "ro": "milsim (simulare militară)", "nl": "milsim (militaire simulatie)",
        "hr": "milsim (vojna simulacija)", "tr": "milsim (askeri simülasyon)",
        "hu": "milsim (katonai szimuláció)", "el": "milsim (στρατιωτική προσομοίωση)",
        "cs": "milsim (vojenská simulace)", "sv": "milsim (militär simulering)",
        "ca": "milsim (simulació militar)", "bg": "милсим (военна симулация)",
        "da": "milsim (militær simulering)",
        "zh": "军事模拟", "ja": "ミルシム",
    },
    "skirmish": {
        "es": "partida", "de": "Gefecht", "fr": "partie", "it": "partita",
        "pt": "partida", "ru": "игра", "pl": "gra", "uk": "гра",
        "ro": "partidă", "nl": "gevecht", "hr": "borba", "tr": "çatışma",
        "hu": "játék", "el": "παιχνίδι", "cs": "hra", "sv": "strid",
        "ca": "partida", "bg": "игра", "da": "kamp",
        "zh": "遭遇战", "ja": "スカーミッシュ",
    },
    "chronograph": {
        "es": "cronógrafo", "de": "Chronograph", "fr": "chronographe",
        "it": "cronografo", "pt": "cronógrafo", "ru": "хронограф",
        "pl": "chronograf", "uk": "хронограф", "ro": "cronograf",
        "nl": "chronograaf", "hr": "kronograf", "tr": "kronograf",
        "hu": "kronográf", "el": "χρονογράφος", "cs": "chronograf",
        "sv": "kronograf", "ca": "cronògraf", "bg": "хронограф",
        "da": "kronograf",
        "zh": "弹速仪", "ja": "弾速計",
    },
    "semi-auto": {
        "es": "semiautomático", "de": "halbautomatisch", "fr": "semi-automatique",
        "it": "semiautomatico", "pt": "semiautomático", "ru": "полуавтоматический",
        "pl": "półautomatyczny", "uk": "напівавтоматичний", "ro": "semiautomat",
        "nl": "halfautomatisch", "hr": "poluautomatski", "tr": "yarı otomatik",
        "hu": "félautomata", "el": "ημιαυτόματο", "cs": "poloautomatický",
        "sv": "halvautomatisk", "ca": "semiautomàtic", "bg": "полуавтоматичен",
        "da": "halvautomatisk",
        "zh": "半自动", "ja": "セミオート",
    },
    "full-auto": {
        "es": "automático", "de": "vollautomatisch", "fr": "automatique",
        "it": "automatico", "pt": "automático", "ru": "автоматический",
        "pl": "automatyczny", "uk": "автоматичний", "ro": "automat",
        "nl": "volautomatisch", "hr": "automatski", "tr": "tam otomatik",
        "hu": "automata", "el": "αυτόματο", "cs": "automatický",
        "sv": "helautomatisk", "ca": "automàtic", "bg": "автоматичен",
        "da": "fuldautomatisk",
        "zh": "全自动", "ja": "フルオート",
    },

    # ══════════════════════════════════════════════════════════════
    # CAMOUFLAGE
    # ══════════════════════════════════════════════════════════════

    "ghillie suit": {
        "es": "traje ghillie", "de": "Ghillie-Anzug", "fr": "tenue ghillie",
        "it": "tuta ghillie", "pt": "traje ghillie", "ru": "маскировочный костюм",
        "pl": "kombinezon ghillie", "uk": "маскувальний костюм", "ro": "costum ghillie",
        "nl": "ghillie pak", "hr": "ghillie odijelo", "tr": "ghillie elbise",
        "hu": "ghillie ruha", "el": "στολή ghillie", "cs": "maskovací oblek ghillie",
        "sv": "ghilliedräkt", "ca": "vestit ghillie", "bg": "маскировъчен костюм",
        "da": "ghillie dragt",
        "zh": "吉利服", "ja": "ギリースーツ",
    },
    "camouflage": {
        "es": "camuflaje", "de": "Tarnung", "fr": "camouflage", "it": "mimetizzazione",
        "pt": "camuflagem", "ru": "камуфляж", "pl": "kamuflaż", "uk": "камуфляж",
        "ro": "camuflaj", "nl": "camouflage", "hr": "kamuflažа", "tr": "kamuflaj",
        "hu": "álcázás", "el": "καμουφλάζ", "cs": "maskování", "sv": "kamouflage",
        "ca": "camuflatge", "bg": "камуфлаж", "da": "camouflage",
        "zh": "迷彩", "ja": "迷彩",
    },
    "face paint": {
        "es": "pintura facial de camuflaje", "de": "Tarnschminke",
        "fr": "peinture de camouflage", "it": "trucco mimetico",
        "pt": "tinta facial de camuflagem", "ru": "маскировочная краска",
        "pl": "farba maskująca", "uk": "маскувальна фарба", "ro": "vopsea de camuflaj",
        "nl": "camouflageverf", "hr": "kamuflažna boja za lice", "tr": "kamuflaj boyası",
        "hu": "álcázó festék", "el": "βαφή καμουφλάζ", "cs": "maskovací barva",
        "sv": "kamouflagefärg", "ca": "pintura facial de camuflatge",
        "bg": "камуфлажна боя", "da": "camouflagemaling",
        "zh": "面部涂装", "ja": "フェイスペイント",
    },
    "camo tape": {
        "es": "cinta de camuflaje", "de": "Tarnband", "fr": "bande de camouflage",
        "it": "nastro mimetico", "pt": "fita de camuflagem", "ru": "камуфляжная лента",
        "pl": "taśma maskująca", "uk": "камуфляжна стрічка", "ro": "bandă de camuflaj",
        "nl": "camouflagetape", "hr": "kamuflažna traka", "tr": "kamuflaj bandı",
        "hu": "álcázó szalag", "el": "ταινία καμουφλάζ", "cs": "maskovací páska",
        "sv": "kamouflagetejp", "ca": "cinta de camuflatge", "bg": "камуфлажна лента",
        "da": "camouflagetape",
        "zh": "迷彩胶带", "ja": "カモテープ",
    },

    # ══════════════════════════════════════════════════════════════
    # COMMUNICATIONS
    # ══════════════════════════════════════════════════════════════

    "radio": {
        "es": "radio", "de": "Funkgerät", "fr": "radio", "it": "radio",
        "pt": "rádio", "ru": "рация", "pl": "radio", "uk": "рація",
        "ro": "stație radio", "nl": "portofoon", "hr": "radio", "tr": "telsiz",
        "hu": "rádió", "el": "ασύρματος", "cs": "vysílačka", "sv": "radio",
        "ca": "ràdio", "bg": "радиостанция", "da": "radio",
        "zh": "对讲机", "ja": "無線機",
    },
    "headset": {
        "es": "auriculares tácticos", "de": "taktisches Headset", "fr": "casque audio tactique",
        "it": "cuffie tattiche", "pt": "headset tático", "ru": "тактическая гарнитура",
        "pl": "słuchawki taktyczne", "uk": "тактична гарнітура", "ro": "cască audio tactică",
        "nl": "tactische headset", "hr": "taktičke slušalice", "tr": "taktik kulaklık",
        "hu": "taktikai headset", "el": "τακτικά ακουστικά", "cs": "taktický headset",
        "sv": "taktiskt headset", "ca": "auriculars tàctics", "bg": "тактически слушалки",
        "da": "taktisk headset",
        "zh": "耳麦", "ja": "ヘッドセット",
    },
    "PTT": {
        "es": "PTT (pulsar para hablar)", "de": "PTT (Push-to-Talk)",
        "fr": "PTT (push-to-talk)", "it": "PTT (push-to-talk)",
        "pt": "PTT (apertar para falar)", "ru": "PTT (тангента)",
        "pl": "PTT (push-to-talk)", "uk": "PTT (тангента)",
        "ro": "PTT (push-to-talk)", "nl": "PTT (push-to-talk)",
        "hr": "PTT (pritisni za govor)", "tr": "PTT (bas-konuş)",
        "hu": "PTT (push-to-talk)", "el": "PTT (push-to-talk)",
        "cs": "PTT (push-to-talk)", "sv": "PTT (push-to-talk)",
        "ca": "PTT (prémer per parlar)", "bg": "PTT (натисни за говорене)",
        "da": "PTT (tryk-for-at-tale)",
        "zh": "PTT", "ja": "PTT",
    },

    # ══════════════════════════════════════════════════════════════
    # NIGHT VISION & THERMAL
    # ══════════════════════════════════════════════════════════════

    "night vision goggles": {
        "es": "gafas de visión nocturna", "de": "Nachtsichtgerät",
        "fr": "lunettes de vision nocturne", "it": "visore notturno",
        "pt": "óculos de visão noturna", "ru": "прибор ночного видения",
        "pl": "noktowizor", "uk": "прилад нічного бачення", "ro": "dispozitiv de vedere nocturnă",
        "nl": "nachtkijker", "hr": "noćni vid", "tr": "gece görüş gözlüğü",
        "hu": "éjjellátó", "el": "συσκευή νυχτερινής όρασης", "cs": "noktovizor",
        "sv": "mörkersikte", "ca": "ulleres de visió nocturna",
        "bg": "уред за нощно виждане", "da": "natsynsbriller",
        "zh": "夜视仪", "ja": "ナイトビジョンゴーグル",
    },
    "thermal sight": {
        "es": "visor térmico", "de": "Wärmebildgerät", "fr": "viseur thermique",
        "it": "visore termico", "pt": "mira térmica", "ru": "тепловизор",
        "pl": "termowizor", "uk": "тепловізор", "ro": "vizor termic",
        "nl": "warmtebeeldkijker", "hr": "termovizija", "tr": "termal nişangah",
        "hu": "hőkamera", "el": "θερμική κάμερα", "cs": "termovize",
        "sv": "värmekamera", "ca": "visor tèrmic", "bg": "термовизор",
        "da": "termisk sigte",
        "zh": "热成像瞄准镜", "ja": "サーマルサイト",
    },

    # ══════════════════════════════════════════════════════════════
    # MATERIALS
    # ══════════════════════════════════════════════════════════════

    "full metal": {
        "es": "full metal", "de": "Vollmetall", "fr": "full métal",
        "it": "full metal", "pt": "full metal", "ru": "фулл метал",
        "pl": "full metal", "uk": "фулл метал", "ro": "full metal",
        "nl": "full metal", "hr": "full metal", "tr": "tam metal",
        "hu": "full metal", "el": "full metal", "cs": "full metal",
        "sv": "full metal", "ca": "full metal", "bg": "фул метал",
        "da": "fuld metal",
        "zh": "全金属", "ja": "フルメタル",
    },
    "polymer": {
        "es": "polímero", "de": "Polymer", "fr": "polymère", "it": "polimero",
        "pt": "polímero", "ru": "полимер", "pl": "polimer", "uk": "полімер",
        "ro": "polimer", "nl": "polymeer", "hr": "polimer", "tr": "polimer",
        "hu": "polimer", "el": "πολυμερές", "cs": "polymer", "sv": "polymer",
        "ca": "polímer", "bg": "полимер", "da": "polymer",
        "zh": "聚合物", "ja": "ポリマー",
    },
    "steel": {
        "es": "acero", "de": "Stahl", "fr": "acier", "it": "acciaio",
        "pt": "aço", "ru": "сталь", "pl": "stal", "uk": "сталь",
        "ro": "oțel", "nl": "staal", "hr": "čelik", "tr": "çelik",
        "hu": "acél", "el": "ατσάλι", "cs": "ocel", "sv": "stål",
        "ca": "acer", "bg": "стомана", "da": "stål",
        "zh": "钢", "ja": "スチール",
    },
    "aluminum alloy": {
        "es": "aleación de aluminio", "de": "Aluminiumlegierung", "fr": "alliage d'aluminium",
        "it": "lega di alluminio", "pt": "liga de alumínio", "ru": "алюминиевый сплав",
        "pl": "stop aluminium", "uk": "алюмінієвий сплав", "ro": "aliaj de aluminiu",
        "nl": "aluminiumlegering", "hr": "aluminijska legura", "tr": "alüminyum alaşım",
        "hu": "alumíniumötvözet", "el": "κράμα αλουμινίου", "cs": "hliníková slitina",
        "sv": "aluminiumlegering", "ca": "aliatge d'alumini", "bg": "алуминиева сплав",
        "da": "aluminiumslegering",
        "zh": "铝合金", "ja": "アルミ合金",
    },

    # ══════════════════════════════════════════════════════════════
    # UPGRADES & INTERNALS
    # ══════════════════════════════════════════════════════════════

    "upgrade": {
        "es": "mejora", "de": "Upgrade", "fr": "amélioration", "it": "potenziamento",
        "pt": "melhoria", "ru": "апгрейд", "pl": "ulepszenie", "uk": "апгрейд",
        "ro": "îmbunătățire", "nl": "upgrade", "hr": "nadogradnja", "tr": "yükseltme",
        "hu": "fejlesztés", "el": "αναβάθμιση", "cs": "vylepšení", "sv": "uppgradering",
        "ca": "millora", "bg": "ъпгрейд", "da": "opgradering",
        "zh": "升级", "ja": "アップグレード",
    },
    "tight bore barrel": {
        "es": "cañón de precisión", "de": "Präzisionslauf", "fr": "canon de précision",
        "it": "canna di precisione", "pt": "cano de precisão", "ru": "прецизионный ствол",
        "pl": "lufa precyzyjna", "uk": "прецизійний стовбур", "ro": "țeavă de precizie",
        "nl": "precisieloop", "hr": "precizna cijev", "tr": "hassas namlu",
        "hu": "precíziós cső", "el": "κάννη ακριβείας", "cs": "přesná hlaveň",
        "sv": "precisionspipa", "ca": "canó de precisió", "bg": "прецизен ствол",
        "da": "præcisionsløb",
        "zh": "精密内管", "ja": "タイトバレル",
    },
    "precision barrel": {
        "es": "cañón de precisión", "de": "Präzisionslauf", "fr": "canon de précision",
        "it": "canna di precisione", "pt": "cano de precisão", "ru": "прецизионный ствол",
        "pl": "lufa precyzyjna", "uk": "прецизійний стовбур", "ro": "țeavă de precizie",
        "nl": "precisieloop", "hr": "precizna cijev", "tr": "hassas namlu",
        "hu": "precíziós cső", "el": "κάννη ακριβείας", "cs": "přesná hlaveň",
        "sv": "precisionspipa", "ca": "canó de precisió", "bg": "прецизен ствол",
        "da": "præcisionsløb",
        "zh": "精密枪管", "ja": "精密バレル",
    },
    "motor": {
        "es": "motor", "de": "Motor", "fr": "moteur", "it": "motore",
        "pt": "motor", "ru": "мотор", "pl": "silnik", "uk": "мотор",
        "ro": "motor", "nl": "motor", "hr": "motor", "tr": "motor",
        "hu": "motor", "el": "κινητήρας", "cs": "motor", "sv": "motor",
        "ca": "motor", "bg": "мотор", "da": "motor",
        "zh": "电机", "ja": "モーター",
    },
    "gear set": {
        "es": "set de engranajes", "de": "Zahnradsatz", "fr": "jeu d'engrenages",
        "it": "set ingranaggi", "pt": "conjunto de engrenagens", "ru": "набор шестерён",
        "pl": "zestaw kół zębatych", "uk": "набір шестерень", "ro": "set de angrenaje",
        "nl": "tandwielset", "hr": "set zupčanika", "tr": "dişli seti",
        "hu": "fogaskerék készlet", "el": "σετ γραναζιών", "cs": "sada ozubených kol",
        "sv": "kugghjulsset", "ca": "joc d'engranatges", "bg": "комплект зъбни колела",
        "da": "tandhjulssæt",
        "zh": "齿轮组", "ja": "ギアセット",
    },
    "wiring": {
        "es": "cableado", "de": "Verkabelung", "fr": "câblage", "it": "cablaggio",
        "pt": "fiação", "ru": "проводка", "pl": "okablowanie", "uk": "проводка",
        "ro": "cablaj", "nl": "bedrading", "hr": "kabliranje", "tr": "kablolama",
        "hu": "kábelezés", "el": "καλωδίωση", "cs": "kabeláž", "sv": "kabeldragning",
        "ca": "cablejat", "bg": "окабеляване", "da": "ledningsføring",
        "zh": "接线", "ja": "配線",
    },

    # ══════════════════════════════════════════════════════════════
    # CONNECTORS
    # ══════════════════════════════════════════════════════════════

    "Deans connector": {
        "es": "conector Deans (T-plug)", "de": "Deans-Stecker (T-Plug)",
        "fr": "connecteur Deans (T-plug)", "it": "connettore Deans (T-plug)",
        "pt": "conector Deans (T-plug)", "ru": "разъём Deans (T-plug)",
        "pl": "złącze Deans (T-plug)", "uk": "роз'єм Deans (T-plug)",
        "ro": "conector Deans (T-plug)", "nl": "Deans-connector (T-plug)",
        "hr": "Deans konektor (T-plug)", "tr": "Deans konektör (T-fiş)",
        "hu": "Deans csatlakozó (T-plug)", "el": "σύνδεσμος Deans (T-plug)",
        "cs": "konektor Deans (T-plug)", "sv": "Deans-kontakt (T-plug)",
        "ca": "connector Deans (T-plug)", "bg": "конектор Deans (T-plug)",
        "da": "Deans-stik (T-plug)",
        "zh": "Deans接头", "ja": "ディーンズコネクター",
    },
    "Tamiya connector": {
        "es": "conector Tamiya", "de": "Tamiya-Stecker", "fr": "connecteur Tamiya",
        "it": "connettore Tamiya", "pt": "conector Tamiya", "ru": "разъём Tamiya",
        "pl": "złącze Tamiya", "uk": "роз'єм Tamiya", "ro": "conector Tamiya",
        "nl": "Tamiya-connector", "hr": "Tamiya konektor", "tr": "Tamiya konektör",
        "hu": "Tamiya csatlakozó", "el": "σύνδεσμος Tamiya", "cs": "konektor Tamiya",
        "sv": "Tamiya-kontakt", "ca": "connector Tamiya", "bg": "конектор Tamiya",
        "da": "Tamiya-stik",
        "zh": "田宫接头", "ja": "タミヤコネクター",
    },
}


# ── Supported languages ────────────────────────────────────────

SUPPORTED_LANGUAGES = {
    "en": "English",
    "es": "Spanish",
    "de": "German",
    "fr": "French",
    "it": "Italian",
    "pt": "Portuguese",
    "ru": "Russian",
    "pl": "Polish",
    "uk": "Ukrainian",
    "ro": "Romanian",
    "nl": "Dutch",
    "hr": "Serbo-Croatian",
    "tr": "Turkish",
    "hu": "Hungarian",
    "el": "Greek",
    "cs": "Czech",
    "sv": "Swedish",
    "ca": "Catalan",
    "bg": "Bulgarian",
    "da": "Danish",
    "zh": "Chinese",
    "ja": "Japanese",
}


def get_glossary_for_pair(source_lang: str, target_lang: str) -> dict:
    """Get glossary dict for a specific language pair.

    Uses English as the hub language:
    - EN→XX: returns {en_term: xx_translation}
    - XX→EN: returns {xx_translation: en_term}
    - XX→YY: returns {xx_translation: yy_translation} (via English hub)
    """
    result = {}

    if source_lang == "en":
        # EN→target: straightforward
        for en_term, translations in GLOSSARY.items():
            if target_lang in translations:
                result[en_term.lower()] = translations[target_lang]
    elif target_lang == "en":
        # source→EN: reverse lookup
        for en_term, translations in GLOSSARY.items():
            if source_lang in translations:
                result[translations[source_lang].lower()] = en_term
    else:
        # XX→YY: go through English hub
        for en_term, translations in GLOSSARY.items():
            if source_lang in translations and target_lang in translations:
                result[translations[source_lang].lower()] = translations[target_lang]

    return result
